#!/usr/bin/env bash
# shellcheck shell=bash
#
# ctx.sh - Portable context switcher for GitHub Copilot CLI
# ==========================================================
#
# Composes AI agent configuration directories (profiles + shared contexts)
# stored under a root directory (default: ~/work/ai-config) into the
# COPILOT_CUSTOM_INSTRUCTIONS_DIRS environment variable, for the current
# shell session.
#
# Compatible with bash and zsh.
#
# ---------------------------------------------------------------------------
# INSTALLATION
# ---------------------------------------------------------------------------
#   1. Copy (or symlink) this file to ~/.config/ctx/ctx.sh
#        mkdir -p ~/.config/ctx
#        cp ctx.sh ~/.config/ctx/ctx.sh
#      (or run ./install.sh from this repo)
#
#   2. zsh setup - add to ~/.zshrc:
#        source "$HOME/.config/ctx/ctx.sh"
#
#   3. bash setup - add to ~/.bashrc:
#        source "$HOME/.config/ctx/ctx.sh"
#
#   4. Completion is registered automatically when this file is sourced.
#
# ---------------------------------------------------------------------------
# DIRECTORY LAYOUT EXPECTED
# ---------------------------------------------------------------------------
#   ${AI_CONFIG_ROOT:-$HOME/work/ai-config}/
#   ├── profiles/
#   │   ├── review/
#   │   ├── architecture/
#   │   ├── incident/
#   │   └── coding/
#   └── shared/
#       ├── dotnet/
#       ├── azure/
#       ├── terraform/
#       └── security/
#
# ---------------------------------------------------------------------------
# USAGE
# ---------------------------------------------------------------------------
#   ctx review                    # activate the "review" profile
#   ctx coding azure              # "coding" profile + "azure" shared context
#   ctx review dotnet security    # profile + multiple shared contexts
#   ctx current                   # show active profile/shared/env vars
#   ctx clear                     # unset AI_CONTEXT / COPILOT_CUSTOM_INSTRUCTIONS_DIRS / COPILOT_HOME
#   ctx clear --all               # remove the current context home and workspace artifacts
#   ctx --help                    # usage help
#
# --- AUTO-LOADING (.ctx files) -----------------------------------------
#   Drop a ".ctx" file in any project directory. Each non-empty, non-comment
#   line maps an arbitrary context name to a custom-instructions directory:
#
#       <context-name>:<path-to-folder>
#
#   Example:
#       review:/home/user/work/ai-config/profiles/review
#       dotnet:/home/user/work/ai-config/shared/dotnet
#       security:./local-instructions
#
#   Relative paths are resolved against the directory containing the .ctx
#   file (not the current working directory). Unlike `ctx <profile> [shared]`,
#   these names are NOT looked up under AI_CONFIG_ROOT/profiles|shared - the
#   path on each line is used directly. Every path is validated to exist.
#
#   When your prompt renders after a `cd` into that directory (or a
#   descendant of it), AI_CONTEXT and COPILOT_CUSTOM_INSTRUCTIONS_DIRS are
#   set (overwriting any previous value) from the file's contents. Leaving
#   the directory tree (into a location with no .ctx file) automatically
#   clears the context.
#
#   SKILL DISCOVERY
#   ----------------
#   COPILOT_CUSTOM_INSTRUCTIONS_DIRS does not make Copilot CLI discover agent
#   skills stored in your .ctx entries. ctx sets COPILOT_HOME to a per-context
#   home and links the resolved .github/skills entries into its skills folder.
#   Shared Copilot files are reconciled against the real Copilot home on every
#   activation. The cache remains after ctx clear; ctx clear --all removes it.
#
#   VS CODE WORKSPACE
#   ------------------
#   Whenever a .ctx file is loaded, a multi-root VS Code workspace file
#   named "<folder-name>.code-workspace" is created (or updated, requires
#   python3) next to it, so the project and its .ctx dependencies can all be
#   browsed in one VS Code window:
#
#     - This folder is added as "root: <folder-name>".
#     - Each .ctx entry is added as "ctx: <context-name>", pointing at the
#       resolved directory from that line.
#
#   Any other folders already present in the workspace file (added by you,
#   or by VS Code) are preserved; only entries previously generated by ctx
#   (named "root: ..." or "ctx: ...") are replaced on each load. Nothing is
#   removed from the workspace file when the context is cleared (run
#   "ctx clear --all" to delete it instead).
#
#   Disable this behavior for the session with:
#       export CTX_AUTO_LOAD=0
#
# ---------------------------------------------------------------------------

# --- Core implementation -----------------------------------------------

_ctx_root() {
    printf '%s\n' "${AI_CONFIG_ROOT:-$HOME/work/ai-config}"
}

_ctx_usage() {
    cat <<'EOF'
Usage:
  ctx <profile> [shared...]   Activate a profile with optional shared contexts
  ctx current                 Show the currently active context
  ctx clear                   Clear the currently active context
  ctx clear --all             Remove the current context home and generated
                               project artifacts next to the nearest .ctx file
  ctx --help | -h             Show this help message

Examples:
  ctx review
  ctx coding azure
  ctx review dotnet security

Environment:
  AI_CONFIG_ROOT      Root directory containing profiles/ and shared/
                       (default: $HOME/work/ai-config)
  CTX_AUTO_LOAD        Set to 0 to disable automatic .ctx loading on cd
EOF
}

_ctx_print_status() {
    local profile="$1"
    local shared_csv="$2"
    local dirs_csv="$3"

    printf '\n[AI Context]\n\n'
    printf 'Profile : %s\n' "${profile:-<none>}"
    printf 'Shared  : %s\n' "${shared_csv:-<none>}"
    printf '\nAI_CONTEXT=%s\n' "${AI_CONTEXT:-<unset>}"
    printf 'COPILOT_HOME=%s\n' "${COPILOT_HOME:-<unset>}"
    printf '\nCOPILOT_CUSTOM_INSTRUCTIONS_DIRS=\n'
    if [ -n "$dirs_csv" ]; then
        printf '%s\n' "$dirs_csv" | tr ',' '\n'
    else
        printf '<unset>\n'
    fi
}

_ctx_current() {
    if [ -z "${AI_CONTEXT:-}" ]; then
        printf 'No active AI context.\n'
        printf 'Run "ctx <profile> [shared...]" to activate one.\n'
        return 0
    fi

    local profile shared_csv
    profile="${AI_CONTEXT%%+*}"
    if [ "$AI_CONTEXT" = "$profile" ]; then
        shared_csv=""
    else
        shared_csv="${AI_CONTEXT#*+}"
        shared_csv="${shared_csv//+/, }"
    fi

    _ctx_print_status "$profile" "$shared_csv" "${COPILOT_CUSTOM_INSTRUCTIONS_DIRS:-}"
}

_ctx_clear() {
    # $1: optional "--all" to also delete the artifacts ctx generates next
    # to the nearest .ctx file (.github/copilot/settings.local.json and the
    # "<folder-name>.code-workspace" file), instead of just leaving them in
    # place for next time.
    local prev_context="${AI_CONTEXT:-}"
    unset AI_CONTEXT
    unset COPILOT_CUSTOM_INSTRUCTIONS_DIRS
    unset COPILOT_HOME

    if [ "${1:-}" = "--all" ]; then
        local dir_of_file="$_ctx_auto_load_dir"
        if [ -z "$dir_of_file" ]; then
            local ctx_file
            if ctx_file="$(_ctx_find_ctx_file)"; then
                dir_of_file="$(dirname "$ctx_file")"
            fi
        fi

        if [ -n "$dir_of_file" ]; then
            local settings_file="$dir_of_file/.github/copilot/settings.local.json"
            if [ -f "$settings_file" ]; then
                # Legacy cleanup: settings.local.json's skillDirectories is
                # confirmed inert (issue #1) and no longer written by ctx,
                # but pre-existing files from older ctx versions are still
                # removed here for one release. Safe to drop this block in
                # a future release once users have upgraded.
                rm -f "$settings_file"
                printf 'ctx: removed %s\n' "$settings_file"
            fi

            local folder_name workspace_file
            folder_name="$(basename "$dir_of_file")"
            workspace_file="$dir_of_file/$folder_name.code-workspace"
            if [ -f "$workspace_file" ]; then
                rm -f "$workspace_file"
                printf 'ctx: removed %s\n' "$workspace_file"
            fi
        else
            if [ -n "$prev_context" ]; then
                # Context was activated manually (no .ctx file), so there are
                # no on-disk artifacts (settings.local.json / workspace file)
                # to clean up, but the COPILOT_HOME directory below still
                # gets removed - don't imply nothing happens at all.
                printf 'ctx: warning: no .ctx file found; skipping artifact cleanup\n' >&2
            else
                printf 'ctx: warning: no .ctx file found; nothing to remove\n' >&2
            fi
        fi

        if [ -n "$prev_context" ]; then
            local sanitized homes_root home_dir
            if [ -n "$_ctx_auto_load_home_override" ]; then
                # This context was loaded from a .ctx file with a "home:"
                # directive (issue #7): its synthetic COPILOT_HOME lives at
                # that custom location, not the centralized default.
                home_dir="$_ctx_auto_load_home_override"
            else
                sanitized="$(_ctx_sanitize_context_name "$prev_context")"
                homes_root="$(_ctx_copilot_home_root)"
                home_dir="$homes_root/$sanitized"
            fi
            if [ -d "$home_dir" ]; then
                rm -rf "$home_dir"
                printf 'ctx: removed %s\n' "$home_dir"
            fi
        fi
    fi

    export CTX_AUTO_LOAD_DIR=""
    _ctx_auto_load_dir=""
    _ctx_auto_load_home_override=""
    printf 'AI context cleared.\n'
}

ctx() {
    if [ "$#" -eq 0 ]; then
        _ctx_usage
        return 0
    fi

    case "$1" in
        -h|--help)
            _ctx_usage
            return 0
            ;;
        current)
            _ctx_current
            return 0
            ;;
        clear)
            _ctx_clear "$2"
            return 0
            ;;
    esac

    local root profile_name profile_dir
    root="$(_ctx_root)"

    if [ ! -d "$root" ]; then
        printf 'ctx: error: AI config root does not exist: %s\n' "$root" >&2
        return 1
    fi

    profile_name="$1"
    shift
    profile_dir="$root/profiles/$profile_name"

    if [ ! -d "$profile_dir" ]; then
        printf 'ctx: error: unknown profile "%s" (looked in %s)\n' "$profile_name" "$root/profiles" >&2
        printf 'ctx: available profiles:\n' >&2
        if [ -d "$root/profiles" ]; then
            find "$root/profiles" -mindepth 1 -maxdepth 1 -type d -exec basename {} \; 2>/dev/null | sed 's/^/  - /' >&2
        fi
        return 1
    fi

    local dirs_csv shared_csv shared_name shared_dir first
    dirs_csv="$profile_dir"
    shared_csv=""
    first=1

    for shared_name in "$@"; do
        shared_dir="$root/shared/$shared_name"
        if [ ! -d "$shared_dir" ]; then
            printf 'ctx: error: unknown shared context "%s" (looked in %s)\n' "$shared_name" "$root/shared" >&2
            printf 'ctx: available shared contexts:\n' >&2
            if [ -d "$root/shared" ]; then
                find "$root/shared" -mindepth 1 -maxdepth 1 -type d -exec basename {} \; 2>/dev/null | sed 's/^/  - /' >&2
            fi
            return 1
        fi
        dirs_csv="$dirs_csv,$shared_dir"
        if [ "$first" -eq 1 ]; then
            shared_csv="$shared_name"
            first=0
        else
            shared_csv="$shared_csv, $shared_name"
        fi
    done

    export COPILOT_CUSTOM_INSTRUCTIONS_DIRS="$dirs_csv"

    if [ -n "$shared_csv" ]; then
        # shellcheck disable=SC2001 # need sed for portable comma->plus with spaces removed
        export AI_CONTEXT="${profile_name}+$(printf '%s' "$shared_csv" | sed 's/, /+/g')"
    else
        export AI_CONTEXT="$profile_name"
    fi

    local -a resolved_dirs_manual=()
    IFS=',' read -r -a resolved_dirs_manual <<< "$dirs_csv"

    _ctx_setup_copilot_home "$AI_CONTEXT" "" "${resolved_dirs_manual[@]}"

    _ctx_print_status "$profile_name" "$shared_csv" "$dirs_csv"
}

# --- Auto-loading via .ctx files ----------------------------------------

_ctx_auto_load_dir=""
# Tracks the "home:" directive override (issue #7), if any, from the last
# .ctx file auto-loaded, so _ctx_clear --all knows to look for the
# synthetic COPILOT_HOME at that location instead of the centralized one.
_ctx_auto_load_home_override=""

_ctx_find_ctx_file() {
    # Search from $PWD upward to the filesystem root for a ".ctx" file.
    local dir="$PWD"
    while [ -n "$dir" ]; do
        if [ -f "$dir/.ctx" ]; then
            printf '%s\n' "$dir/.ctx"
            return 0
        fi
        [ "$dir" = "/" ] && break
        dir="$(dirname "$dir")"
    done
    return 1
}

_ctx_auto_load_hook() {
    [ "${CTX_AUTO_LOAD:-1}" = "0" ] && return 0

    local ctx_file
    if ctx_file="$(_ctx_find_ctx_file)"; then
        local dir_of_file
        dir_of_file="$(dirname "$ctx_file")"
        if [ "$_ctx_auto_load_dir" != "$dir_of_file" ]; then
            if _ctx_load_ctx_file "$ctx_file"; then
                _ctx_auto_load_dir="$dir_of_file"
            fi
        fi
    else
        if [ -n "$_ctx_auto_load_dir" ]; then
            _ctx_clear
            _ctx_auto_load_dir=""
        fi
    fi
}

_ctx_copilot_home_root() {
    printf '%s\n' "${AI_CONFIG_ROOT:+}" >/dev/null # no-op, keeps shellcheck quiet about unused pattern
    printf '%s\n' "${CTX_HOMES_ROOT:-$HOME/.config/ctx/homes}"
}

_ctx_sanitize_context_name() {
    # Sanitizes a context name for safe use as a single path component.
    # '+' is already filesystem-safe and left as-is. Any '/' or other
    # unsafe character is replaced with '_' defensively.
    local name="$1"
    printf '%s' "$name" | tr -c 'A-Za-z0-9+._-' '_'
}

# List of files (relative to a COPILOT_HOME dir / ~/.copilot) that get
# symlinked back to the real ~/.copilot so global auth/config/session
# history keep working identically across all contexts. This is also the
# authoritative list the 3.4a reconciliation loop walks on every
# activation to detect + repair a symlink that Copilot CLI silently
# replaced with a plain file via rename(tmp, path).
_ctx_copilot_home_shared_files() {
    cat <<'EOF'
settings.json
config.json
mcp-config.json
session-store.db
session-store.db-shm
session-store.db-wal
EOF
}

# Directories symlinked back to the real ~/.copilot the same way (treated
# defensively with the same reconciliation, even though only files were
# empirically observed broken - see plan section 3.4a).
_ctx_copilot_home_shared_dirs() {
    cat <<'EOF'
session-state
installed-plugins
logs
EOF
}

_ctx_reconcile_symlink() {
    # Ensures $home_dir/$name is a symlink pointing at $real_target,
    # self-healing the confirmed rename()-through-symlink hazard (plan
    # 3.4a): if Copilot CLI (or anything else) replaced the symlink with
    # a plain file/dir holding new data, that data is copied back onto
    # the real ~/.copilot target *before* the symlink is recreated, so
    # the most recent write is preserved rather than silently lost.
    #
    # $1: home_dir   $2: name (relative path under home_dir)
    # $3: real_target (absolute path under ~/.copilot)
    # $4: kind - "file" or "dir"
    local home_dir="$1" name="$2" real_target="$3" kind="$4"
    local link_path="$home_dir/$name"

    if [ -L "$link_path" ]; then
        local current_target
        current_target="$(readlink "$link_path")"
        if [ "$current_target" = "$real_target" ]; then
            # Already correct; no-op (idempotency, plan 3.4).
            return 0
        fi
        # Stale/incorrect symlink target - remove and recreate below.
        rm -f "$link_path"
    elif [ -e "$link_path" ]; then
        # Not a symlink but exists: the confirmed hazard from 3.4a - the
        # CLI's write-tmp+rename() replaced our symlink with a real file
        # (or, defensively, a real dir) holding this context's latest
        # data. Copy it over the real target so the write is not lost,
        # then remove it and recreate the symlink.
        mkdir -p "$(dirname "$real_target")"
        if [ "$kind" = "dir" ]; then
            rm -rf "$real_target"
            cp -a "$link_path" "$real_target"
            rm -rf "$link_path"
        else
            cp -f "$link_path" "$real_target"
            rm -f "$link_path"
        fi
    fi

    if [ ! -e "$link_path" ]; then
        mkdir -p "$(dirname "$link_path")"
        if [ "$kind" = "dir" ]; then
            mkdir -p "$real_target"
        else
            mkdir -p "$(dirname "$real_target")"
            [ -e "$real_target" ] || : > "$real_target"
        fi
        if ! ln -s "$real_target" "$link_path" 2>/dev/null; then
            printf 'ctx: warning: could not create symlink %s -> %s\n' "$link_path" "$real_target" >&2
            return 1
        fi
    fi
    return 0
}

_ctx_setup_copilot_home() {
    # $1: context-name (raw, e.g. "review+test")
    # $2: home-dir override (absolute path) or "" to use the centralized
    #     default. Set via the .ctx file's optional "home:<path>" directive
    #     (issue #7); manual "ctx <profile>..." invocations always pass "".
    # remaining args: resolved directories for the active context
    local context_name="$1"
    local home_override="$2"
    shift 2
    local -a resolved_dirs=("$@")

    local sanitized homes_root home_dir copilot_dir
    if [ -n "$home_override" ]; then
        home_dir="$home_override"
    else
        sanitized="$(_ctx_sanitize_context_name "$context_name")"
        homes_root="$(_ctx_copilot_home_root)"
        home_dir="$homes_root/$sanitized"
    fi
    copilot_dir="${CTX_COPILOT_DIR:-$HOME/.copilot}"

    mkdir -p "$home_dir/skills" || {
        printf 'ctx: warning: could not create %s; leaving COPILOT_HOME unset\n' "$home_dir" >&2
        return 1
    }
    mkdir -p "$copilot_dir" 2>/dev/null || true

    local ok=1
    local f
    while IFS= read -r f; do
        [ -z "$f" ] && continue
        _ctx_reconcile_symlink "$home_dir" "$f" "$copilot_dir/$f" "file" || ok=0
    done <<EOF
$(_ctx_copilot_home_shared_files)
EOF

    local d
    while IFS= read -r d; do
        [ -z "$d" ] && continue
        _ctx_reconcile_symlink "$home_dir" "$d" "$copilot_dir/$d" "dir" || ok=0
    done <<EOF
$(_ctx_copilot_home_shared_dirs)
EOF

    if [ "$ok" -ne 1 ]; then
        printf 'ctx: warning: one or more COPILOT_HOME symlinks could not be created; leaving COPILOT_HOME unset for this session\n' >&2
        return 1
    fi

    # Reconcile skills/: desired (name -> target) pairs come from each
    # resolved dir's .github/skills subfolder, if present.
    local -A desired_skills=()
    local rd skill_dir sname
    for rd in "${resolved_dirs[@]}"; do
        skill_dir="$rd/.github/skills"
        [ -d "$skill_dir" ] || continue
        local s
        for s in "$skill_dir"/*/; do
            [ -d "$s" ] || continue
            sname="$(basename "$s")"
            desired_skills["$sname"]="${s%/}"
        done
    done

    # Remove stale skill symlinks no longer in desired set.
    if [ -d "$home_dir/skills" ]; then
        local existing
        for existing in "$home_dir/skills"/*; do
            [ -e "$existing" ] || continue
            local ename
            ename="$(basename "$existing")"
            if [ -z "${desired_skills[$ename]:-}" ]; then
                # Skills are directory symlinks; rm -rf mirrors
                # _ctx_reconcile_symlink and the PowerShell equivalent
                # (Remove-Item -Recurse -Force).
                rm -rf "$existing"
            fi
        done
    fi

    # Create/repair desired skill symlinks (idempotent).
    local name target link
    for name in "${!desired_skills[@]}"; do
        target="${desired_skills[$name]}"
        link="$home_dir/skills/$name"
        if [ -L "$link" ] && [ "$(readlink "$link")" = "$target" ]; then
            continue
        fi
        rm -rf "$link"
        if ! ln -s "$target" "$link" 2>/dev/null; then
            printf 'ctx: warning: could not create skill symlink %s -> %s\n' "$link" "$target" >&2
        fi
    done

    export COPILOT_HOME="$home_dir"
    return 0
}

_ctx_update_skill_directories() {
    # Merges the given skill directories (remaining args) into the
    # "skillDirectories" array of .github/copilot/settings.local.json located
    # under $1 (the directory containing the .ctx file). Creates the file
    # (and any missing parent directories) if it does not already exist.
    # Preserves any other keys, and any pre-existing skillDirectories entries,
    # already in the file.
    local base_dir="$1"
    shift
    [ "$#" -eq 0 ] && return 0

    local settings_dir="$base_dir/.github/copilot"
    local settings_file="$settings_dir/settings.local.json"

    local python_bin=""
    if command -v python3 >/dev/null 2>&1; then
        python_bin="python3"
    elif command -v python >/dev/null 2>&1; then
        python_bin="python"
    else
        printf 'ctx: warning: python3 not found; cannot update %s with skill directories\n' "$settings_file" >&2
        return 0
    fi

    mkdir -p "$settings_dir"

    "$python_bin" - "$settings_file" "$@" <<'PYEOF'
import json
import sys

settings_file = sys.argv[1]
new_dirs = sys.argv[2:]

settings = {}
try:
    with open(settings_file, "r", encoding="utf-8") as f:
        content = f.read().strip()
        if content:
            settings = json.loads(content)
except (FileNotFoundError, json.JSONDecodeError):
    settings = {}

if not isinstance(settings, dict):
    settings = {}

existing = settings.get("skillDirectories") or []
if not isinstance(existing, list):
    existing = []

merged = list(dict.fromkeys(existing + new_dirs))
settings["skillDirectories"] = merged

with open(settings_file, "w", encoding="utf-8") as f:
    json.dump(settings, f, indent=2)
    f.write("\n")
PYEOF
}

_ctx_update_workspace_file() {
    # Creates/updates a "<folder-name>.code-workspace" file next to the .ctx
    # file (under $1, the directory containing the .ctx file) so the project
    # and its .ctx dependencies can be browsed together in VS Code: this
    # folder is added as "root: <name>", and each .ctx entry (remaining
    # args, given as alternating name/path pairs) is added as
    # "ctx: <context-name>". Folders not generated by ctx (i.e. not named
    # "root: ..." / "ctx: ...") are left untouched; other top-level keys
    # (settings, extensions, ...) already in the file are preserved.
    local base_dir="$1"
    shift
    local folder_name
    folder_name="$(basename "$base_dir")"
    local workspace_file="$base_dir/$folder_name.code-workspace"

    local python_bin=""
    if command -v python3 >/dev/null 2>&1; then
        python_bin="python3"
    elif command -v python >/dev/null 2>&1; then
        python_bin="python"
    else
        printf 'ctx: warning: python3 not found; cannot update %s with workspace folders\n' "$workspace_file" >&2
        return 0
    fi

    "$python_bin" - "$workspace_file" "$folder_name" "$@" <<'PYEOF'
import json
import sys

workspace_file = sys.argv[1]
folder_name = sys.argv[2]
rest = sys.argv[3:]

pairs = [(rest[i], rest[i + 1]) for i in range(0, len(rest), 2)]

workspace = {}
try:
    with open(workspace_file, "r", encoding="utf-8") as f:
        content = f.read().strip()
        if content:
            workspace = json.loads(content)
except (FileNotFoundError, json.JSONDecodeError):
    workspace = {}

if not isinstance(workspace, dict):
    workspace = {}

existing = workspace.get("folders") or []
if not isinstance(existing, list):
    existing = []

user_folders = [
    f for f in existing
    if not (isinstance(f, dict) and isinstance(f.get("name"), str)
            and (f["name"].startswith("root: ") or f["name"].startswith("ctx: ")))
]

root_entry = {"path": ".", "name": f"root: {folder_name}"}
ctx_entries = [{"path": path, "name": f"ctx: {name}"} for name, path in pairs]

workspace["folders"] = [root_entry] + ctx_entries + user_folders
workspace.setdefault("settings", {})

with open(workspace_file, "w", encoding="utf-8") as f:
    json.dump(workspace, f, indent=2)
    f.write("\n")
PYEOF
}

_ctx_load_ctx_file() {
    # Parses a .ctx file where each non-empty, non-comment line is
    # "<context-name>:<path-to-folder>". Relative paths are resolved
    # against the directory containing the .ctx file. Sets AI_CONTEXT and
    # COPILOT_CUSTOM_INSTRUCTIONS_DIRS directly from the parsed entries.
    #
    # An optional line "home:<path>" (issue #7) is a reserved directive,
    # not a profile/shared-context entry: it overrides where this .ctx
    # file's synthetic COPILOT_HOME is created, instead of the centralized
    # default under _ctx_copilot_home_root. Its path resolves the same way
    # (relative to the .ctx file's directory unless absolute), and the
    # directory does not need to pre-exist (it's created on demand, same
    # as the centralized default).
    local ctx_file="$1"
    local dir_of_file
    dir_of_file="$(dirname "$ctx_file")"

    local ai_context="" dirs_csv="" first_name="" home_override=""
    local line name path resolved_path
    local -a resolved_dirs=()
    local -a resolved_names=()

    while IFS= read -r line || [ -n "$line" ]; do
        line="${line%$'\r'}"
        [ -z "$line" ] && continue
        case "$line" in
            '#'*) continue ;;
        esac
        case "$line" in
            *:*) : ;;
            *)
                printf 'ctx: error: invalid .ctx line in %s (expected <name>:<path>): %s\n' "$ctx_file" "$line" >&2
                return 1
                ;;
        esac

        name="${line%%:*}"
        path="${line#*:}"
        # Trim leading/trailing whitespace so "home: .copilot-ctx" (with a
        # space after the colon, as shown in docs/examples) parses the same
        # as "home:.copilot-ctx" - matches ctx.ps1's .Trim() on both sides.
        name="${name#"${name%%[![:space:]]*}"}"
        name="${name%"${name##*[![:space:]]}"}"
        path="${path#"${path%%[![:space:]]*}"}"
        path="${path%"${path##*[![:space:]]}"}"
        if [ -z "$name" ] || [ -z "$path" ]; then
            printf 'ctx: error: invalid .ctx line in %s (expected <name>:<path>): %s\n' "$ctx_file" "$line" >&2
            return 1
        fi

        case "$path" in
            /*) resolved_path="$path" ;;
            *) resolved_path="$dir_of_file/$path" ;;
        esac

        if [ "$name" = "home" ]; then
            if [ -n "$home_override" ]; then
                printf 'ctx: error: duplicate "home:" directive in %s\n' "$ctx_file" >&2
                return 1
            fi
            home_override="$resolved_path"
            continue
        fi

        if [ ! -d "$resolved_path" ]; then
            printf 'ctx: error: .ctx entry "%s" in %s points to missing directory: %s\n' "$name" "$ctx_file" "$resolved_path" >&2
            return 1
        fi

        if [ -z "$ai_context" ]; then
            ai_context="$name"
            dirs_csv="$resolved_path"
            first_name="$name"
        else
            ai_context="$ai_context+$name"
            dirs_csv="$dirs_csv,$resolved_path"
        fi
        resolved_dirs+=("$resolved_path")
        resolved_names+=("$name")
    done < "$ctx_file"

    if [ -z "$ai_context" ]; then
        printf 'ctx: error: .ctx file is empty or invalid: %s\n' "$ctx_file" >&2
        return 1
    fi

    # Setting COPILOT_CUSTOM_INSTRUCTIONS_DIRS alone does not make Copilot CLI
    # load skills from these directories. Genuine per-folder, session-
    # isolated skill discovery is provided via COPILOT_HOME (see
    # _ctx_setup_copilot_home) rather than settings.local.json's
    # skillDirectories, which Copilot CLI silently ignores (issue #1).

    # Create/update "<folder-name>.code-workspace" next to the .ctx file so
    # this project and its .ctx dependencies can be browsed together in one
    # VS Code window (name/path pairs, alternating).
    local -a workspace_pairs=()
    local i
    for ((i = 0; i < ${#resolved_names[@]}; i++)); do
        workspace_pairs+=("${resolved_names[$i]}" "${resolved_dirs[$i]}")
    done
    _ctx_update_workspace_file "$dir_of_file" "${workspace_pairs[@]}"

    export AI_CONTEXT="$ai_context"
    export COPILOT_CUSTOM_INSTRUCTIONS_DIRS="$dirs_csv"

    _ctx_setup_copilot_home "$ai_context" "$home_override" "${resolved_dirs[@]}"
    _ctx_auto_load_home_override="$home_override"

    local shared_csv
    if [ "$ai_context" = "$first_name" ]; then
        shared_csv=""
    else
        shared_csv="${ai_context#*+}"
        shared_csv="${shared_csv//+/, }"
    fi

    _ctx_print_status "$first_name" "$shared_csv" "$dirs_csv"
}

# --- Shell integration (completion + chdir hooks) -----------------------

_ctx_list_subdirs() {
    local base="$1"
    [ -d "$base" ] || return 0
    find "$base" -mindepth 1 -maxdepth 1 -type d -exec basename {} \; 2>/dev/null
}

if [ -n "${ZSH_VERSION:-}" ]; then
    # zsh completion
    _ctx_zsh_complete() {
        local root="$(_ctx_root)"
        local -a words_arr
        words_arr=("${words[@]}")
        if [ "${#words_arr[@]}" -eq 3 ] && [ "${words_arr[2]}" = "clear" ]; then
            compadd --all
        elif [ "${#words_arr[@]}" -le 2 ]; then
            local -a profiles
            profiles=("${(f)$(_ctx_list_subdirs "$root/profiles")}")
            compadd current clear -- "${profiles[@]}"
        else
            local -a shared
            shared=("${(f)$(_ctx_list_subdirs "$root/shared")}")
            compadd -- "${shared[@]}"
        fi
    }
    compdef _ctx_zsh_complete ctx 2>/dev/null || true

    autoload -Uz add-zsh-hook 2>/dev/null
    if command -v add-zsh-hook >/dev/null 2>&1; then
        add-zsh-hook chpwd _ctx_auto_load_hook
    fi
    # Run once for the shell's starting directory.
    _ctx_auto_load_hook

elif [ -n "${BASH_VERSION:-}" ]; then
    # bash completion
    _ctx_bash_complete() {
        local root cur
        root="$(_ctx_root)"
        cur="${COMP_WORDS[COMP_CWORD]}"

        if [ "$COMP_CWORD" -eq 1 ]; then
            mapfile -t COMPREPLY < <(compgen -W "current clear $(_ctx_list_subdirs "$root/profiles" | tr '\n' ' ')" -- "$cur")
        elif [ "$COMP_CWORD" -eq 2 ] && [ "${COMP_WORDS[1]}" = "clear" ]; then
            mapfile -t COMPREPLY < <(compgen -W "--all" -- "$cur")
        else
            mapfile -t COMPREPLY < <(compgen -W "$(_ctx_list_subdirs "$root/shared" | tr '\n' ' ')" -- "$cur")
        fi
    }
    complete -F _ctx_bash_complete ctx

    _ctx_bash_chpwd() {
        if [ "${_ctx_bash_last_pwd:-}" != "$PWD" ]; then
            _ctx_bash_last_pwd="$PWD"
            _ctx_auto_load_hook
        fi
    }
    case "${PROMPT_COMMAND:-}" in
        *_ctx_bash_chpwd*) : ;;
        "") PROMPT_COMMAND="_ctx_bash_chpwd" ;;
        *) PROMPT_COMMAND="_ctx_bash_chpwd;${PROMPT_COMMAND}" ;;
    esac
    # Run once for the shell's starting directory.
    _ctx_bash_last_pwd="$PWD"
    _ctx_auto_load_hook
fi
