#Requires -Version 5.1
<#
.SYNOPSIS
    ctx - Portable context switcher for GitHub Copilot CLI (PowerShell edition)

.DESCRIPTION
    Composes AI agent configuration directories (profiles)
    stored under a root directory (default: $HOME\work\ai-config) into the
    COPILOT_CUSTOM_INSTRUCTIONS_DIRS environment variable, for the current
    PowerShell session.

    Mirrors the behavior of ctx.sh (bash/zsh) so the same workflow works on
    Windows PowerShell and PowerShell 7+ (pwsh).

.NOTES
    INSTALLATION
    ------------
    1. Copy this file to a stable location, e.g.:
         %USERPROFILE%\.config\ctx\ctx.ps1
       (or run .\install.ps1 from this repo)

    2. Add to your PowerShell profile ($PROFILE):
         . "$HOME\.config\ctx\ctx.ps1"

    3. Tab completion and directory-change auto-loading are registered
       automatically when this file is dot-sourced.

    DIRECTORY LAYOUT EXPECTED
    -------------------------
        $env:AI_CTX_PROFILES_CONFIG_ROOT (default: $HOME\work\ai-config)
        `-- profiles\
            |-- review\
            |-- architecture\
            |-- incident\
            |-- coding\
            |-- dotnet\
            |-- azure\
            |-- terraform\
            `-- security\

    USAGE
    -----
        ctx review                    # activate the "review" profile
        ctx coding azure               # activate multiple profiles
        ctx review dotnet security     # activate multiple profiles
        ctx current                    # show active profiles/env vars
        ctx clear                      # unset AI_CTX_PROFILES / COPILOT_CUSTOM_INSTRUCTIONS_DIRS / COPILOT_HOME
        ctx clear --all                # remove the current context home and owned workspace artifacts
        ctx --help                     # usage help

    AUTO-LOADING (.ctx files)
    --------------------------
    Drop a ".ctx" file in any project directory. Each non-empty,
    non-comment line maps an arbitrary context name to a custom-instructions
    directory:

        <context-name>:<path-to-folder>

    Example:
        review:C:\work\ai-config\profiles\review
        dotnet:C:\work\ai-config\profiles\dotnet
        security:.\local-instructions

    Relative paths are resolved against the directory containing the .ctx
    file (not the current working directory). Unlike `ctx <profile>
    [profile...]`, these names are NOT looked up under AI_CTX_PROFILES_CONFIG_ROOT\profiles
    - the path on each line is used directly. Every path is validated
    to exist.

    When your prompt renders after a `cd`/`Set-Location` into that directory
    (or a descendant of it), AI_CTX_PROFILES and COPILOT_CUSTOM_INSTRUCTIONS_DIRS
    are set (overwriting any previous value) from the file's contents.
    Leaving the directory tree (into a location with no .ctx file)
    automatically clears the context.

    SKILL DISCOVERY
    ---------------
    COPILOT_CUSTOM_INSTRUCTIONS_DIRS does not make Copilot CLI discover
    agent skills stored in your .ctx entries. ctx sets COPILOT_HOME to a
    per-context home and links resolved .github\skills entries into its
    skills folder. Shared Copilot files are reconciled against the real
    Copilot home on every activation. The cache remains after ctx clear;
    ctx clear --all removes it.

    VS CODE WORKSPACE
    ------------------
    Whenever a .ctx file is loaded, a multi-root VS Code workspace file
    named "<folder-name>.code-workspace" is created (or updated) next to
    it, so the project and its .ctx dependencies can all be browsed in one
    VS Code window:

        - This folder is added as "root: <folder-name>".
        - Each .ctx entry is added as "ctx: <context-name>", pointing at
          the resolved directory from that line.

    Any other folders already present in the workspace file (added by you,
    or by VS Code) are preserved; only entries previously generated by ctx
    (named "root: ..." or "ctx: ...") are replaced on each load. Nothing is
    removed from the workspace file when the context is cleared (run
    "ctx clear --all" to delete it instead).

    Disable this behavior for the session with:
        $env:CTX_AUTO_LOAD = "0"
#>

# --- Core implementation -------------------------------------------------

function Get-CtxRoot {
    if ($env:AI_CTX_PROFILES_CONFIG_ROOT) {
        return $env:AI_CTX_PROFILES_CONFIG_ROOT
    }
    return (Join-Path $HOME 'work\ai-config')
}

function Show-CtxUsage {
    @'
Usage:
  ctx <profile> [profile...]  Activate one or more profiles
  ctx current                   Show the currently active context
  ctx check                    Read-only audit against the nearest .ctx file
  ctx clear                   Clear the currently active context
  ctx clear --all             Remove the current context home and generated
                               project artifacts next to the nearest .ctx file
                               Workspace files are removed only with the exact
                               generatedBy: "ctx" marker; unmarked, invalid,
                               and linked workspaces are preserved with a warning.
  ctx --help | -h             Show this help message

Examples:
  ctx review
  ctx coding azure
  ctx review dotnet security

Environment:
  AI_CTX_PROFILES_CONFIG_ROOT      Root directory containing profiles\
                       (default: $HOME\work\ai-config)
  CTX_AUTO_LOAD        Set to 0 to disable automatic .ctx loading on cd
'@ | Write-Host
}

function Write-CtxStatus {
    param(
        [string]$ProfileName,
        [string]$SharedCsv,
        [string]$DirsCsv
    )

    Write-Host ""
    Write-Host "[AI Context]"
    Write-Host ""
    Write-Host "Profile : $(if ($ProfileName) { $ProfileName } else { '<none>' })"
    Write-Host "Profiles: $(if ($SharedCsv) { $SharedCsv } else { '<none>' })"
    Write-Host ""
    Write-Host "AI_CTX_PROFILES=$(if ($env:AI_CTX_PROFILES) { $env:AI_CTX_PROFILES } else { '<unset>' })"
    Write-Host "COPILOT_HOME=$(if ($env:COPILOT_HOME) { $env:COPILOT_HOME } else { '<unset>' })"
    Write-Host ""
    Write-Host "COPILOT_CUSTOM_INSTRUCTIONS_DIRS="
    if ($DirsCsv) {
        ($DirsCsv -split ',') | ForEach-Object { Write-Host $_ }
    } else {
        Write-Host "<unset>"
    }
}

function Show-CtxCurrent {
    if (-not $env:AI_CTX_PROFILES) {
        Write-Host "No active AI context."
        Write-Host 'Run "ctx <profile> [profile...]" to activate one.'
        return
    }

    $parts = $env:AI_CTX_PROFILES -split '\+'
    $profileName = $parts[0]
    $sharedCsv = ($parts | Select-Object -Skip 1) -join ', '

    Write-CtxStatus -ProfileName $profileName -SharedCsv $sharedCsv -DirsCsv $env:COPILOT_CUSTOM_INSTRUCTIONS_DIRS
}

function Clear-CtxContext {
    param([switch]$All)

    $prevContext = $env:AI_CTX_PROFILES
    $prevHome = $env:COPILOT_HOME
    $cleanupFailed = $false
    Remove-Item Env:\AI_CTX_PROFILES -ErrorAction SilentlyContinue
    Remove-Item Env:\COPILOT_CUSTOM_INSTRUCTIONS_DIRS -ErrorAction SilentlyContinue
    Remove-Item Env:\COPILOT_HOME -ErrorAction SilentlyContinue

    if ($All) {
        $dirOfFile = $Script:CtxAutoLoadDir
        if (-not $dirOfFile) {
            $ctxFile = Find-CtxFile
            if ($ctxFile) {
                $dirOfFile = Split-Path -Parent $ctxFile
            }
        }

        if ($dirOfFile) {
            # Legacy cleanup: settings.local.json's skillDirectories is
            # confirmed inert (issue #1) and no longer written by ctx, but
            # pre-existing files from older ctx versions are still removed
            # here for one release. Safe to drop this block in a future
            # release once users have upgraded.
            $settingsFile = Join-Path $dirOfFile '.github\copilot\settings.local.json'
            if (Test-Path -LiteralPath $settingsFile -PathType Leaf) {
                try {
                    Remove-Item -LiteralPath $settingsFile -Force -ErrorAction Stop
                    Write-Host "ctx: removed $settingsFile"
                } catch {
                    $cleanupFailed = $true
                    Write-Error "ctx: error: failed to remove $settingsFile`: $_" -ErrorAction Continue
                }
            }

            $folderName = Split-Path -Leaf (Resolve-Path -LiteralPath $dirOfFile).Path
            $workspaceFile = Join-Path $dirOfFile "$folderName.code-workspace"
            $workspaceItem = Get-Item -LiteralPath $workspaceFile -Force -ErrorAction SilentlyContinue
            if ($workspaceItem -and ($workspaceItem.Attributes -band [IO.FileAttributes]::ReparsePoint) -ne 0) {
                Write-Warning "ctx: preserved linked workspace $workspaceFile"
            } elseif ($workspaceItem) {
                $workspaceOwned = $false
                try {
                    $workspaceData = Get-Content -LiteralPath $workspaceFile -Raw | ConvertFrom-Json
                    $workspaceOwned = ($workspaceData.generatedBy -is [string]) -and ($workspaceData.generatedBy -ceq 'ctx')
                } catch {
                    $workspaceOwned = $false
                }
                if ($workspaceOwned) {
                    try {
                        Remove-Item -LiteralPath $workspaceFile -Force -ErrorAction Stop
                        Write-Host "ctx: removed $workspaceFile"
                    } catch {
                        $cleanupFailed = $true
                        Write-Error "ctx: error: failed to remove $workspaceFile`: $_" -ErrorAction Continue
                    }
                } else {
                    Write-Warning "ctx: preserved unowned workspace $workspaceFile"
                }
            }
        } else {
            if ($prevContext) {
                # Context was activated manually (no .ctx file), so there are
                # no on-disk artifacts (settings.local.json / workspace file)
                # to clean up, but the COPILOT_HOME directory below still
                # gets removed - don't imply nothing happens at all.
                Write-Warning "ctx: warning: no .ctx file found; skipping artifact cleanup"
            } else {
                Write-Warning "ctx: warning: no .ctx file found; nothing to remove"
            }
        }

        if ($prevContext) {
            if ($Script:CtxAutoLoadHomeOverride) {
                $homeDir = $Script:CtxAutoLoadHomeOverride
            } else {
                $sanitized = Get-CtxSanitizedContextName -Name $prevContext
                $homesRoot = Get-CtxCopilotHomeRoot
                $homeDir = Join-Path $homesRoot $sanitized
            }
            if (-not $prevHome -or $homeDir -ne $prevHome) {
                Write-Error "ctx: error: refusing to remove unsafe or unselected home: $homeDir" -ErrorAction Continue
                return $false
            }
            try { $null = Get-CtxValidatedHomePath -Path $homeDir } catch { Write-Error "ctx: error: $_" -ErrorAction Continue; return $false }
            # TOCTOU hardening (issue #17): revalidate immediately before
            # the recursive delete below, unconditionally - see the
            # comment block above Get-CtxValidatedHomePath for the
            # attacker model and limitations. Invoke-CtxToctouHook is the
            # same test-only seam used in Set-CtxCopilotHome, absent in
            # normal operation.
            Invoke-CtxToctouHook
            try { $null = Get-CtxValidatedHomePath -Path $homeDir } catch { Write-Error "ctx: error: $_" -ErrorAction Continue; return $false }
            if ((Test-Path -LiteralPath $homeDir -PathType Container) -and -not (Test-CtxIsLink -Path $homeDir)) {
                try {
                    Remove-Item -LiteralPath $homeDir -Recurse -Force -ErrorAction Stop
                } catch {
                    Write-Error "ctx: error: failed to remove $homeDir`: $_" -ErrorAction Continue
                    return $false
                }
                Write-Host "ctx: removed $homeDir"
            }
        }
    }

    $Script:CtxAutoLoadDir = $null
    $Script:CtxAutoLoadHomeOverride = $null
    Write-Host "AI context cleared."
    return (-not $cleanupFailed)
}

function Resolve-CtxProfileIdentifier {
    # Profiles are identifiers, not paths. The canonical target must remain an
    # immediate child of the canonical profiles root, including through links.
    param([string]$Name)
    if ([string]::IsNullOrWhiteSpace($Name) -or $Name -in @('.', '..') -or $Name -match '[\\/]') {
        throw "invalid profile identifier `"$Name`""
    }
    $profilesRoot = Join-Path (Get-CtxRoot) 'profiles'
    $rootCanonical = [System.IO.Path]::GetFullPath($profilesRoot).TrimEnd([System.IO.Path]::DirectorySeparatorChar, [System.IO.Path]::AltDirectorySeparatorChar)
    $candidate = Join-Path $profilesRoot $Name
    if (-not (Test-Path -LiteralPath $candidate -PathType Container)) {
        throw "unknown profile `"$Name`" (looked in $profilesRoot)"
    }
    $canonical = (Resolve-Path -LiteralPath $candidate).Path.TrimEnd([System.IO.Path]::DirectorySeparatorChar, [System.IO.Path]::AltDirectorySeparatorChar)
    if (-not ([string]::Equals((Split-Path -Parent $canonical), $rootCanonical, [System.StringComparison]::OrdinalIgnoreCase))) {
        throw "invalid profile identifier `"$Name`""
    }
    return $canonical
}

function ctx {
    param(
        [Parameter(ValueFromRemainingArguments = $true)]
        [string[]]$Contexts
    )

    if (-not $Contexts -or $Contexts.Count -eq 0) {
        Show-CtxUsage
        return
    }

    switch ($Contexts[0]) {
        { $_ -in @('-h', '--help') } {
            Show-CtxUsage
            return
        }
        'current' {
            Show-CtxCurrent
            return
        }
        'check' {
            return (Test-CtxActivation)
        }
        'clear' {
            $all = $Contexts.Count -gt 1 -and $Contexts[1] -eq '--all'
            return (Clear-CtxContext -All:$all)
        }
    }

    $root = Get-CtxRoot
    if (-not (Test-Path -LiteralPath $root -PathType Container)) {
        Write-Error "ctx: error: AI config root does not exist: $root"
        return
    }

    $profileName = $Contexts[0]
    $profileNames = @()
    $seenNames = @{}
    $dirsList = @()
    foreach ($name in $Contexts) {
        $key = $name.ToLowerInvariant()
        if ($seenNames.ContainsKey($key)) { Write-Error "ctx: error: duplicate profile `"$name`""; return }
        $seenNames[$key] = $name
        try { $profileDir = Resolve-CtxProfileIdentifier -Name $name } catch { Write-Error "ctx: error: $_"; return }
        $profileNames += $name
        $dirsList += $profileDir
    }

    $dirsCsv = $dirsList -join ','
    $sharedCsv = ""

    $env:COPILOT_CUSTOM_INSTRUCTIONS_DIRS = $dirsCsv
    $env:AI_CTX_PROFILES = $profileNames -join '+'

    Set-CtxCopilotHome -ContextName $env:AI_CTX_PROFILES -ResolvedDirs $dirsList

    Write-CtxStatus -ProfileName $profileName -SharedCsv $sharedCsv -DirsCsv $dirsCsv
}

# --- Auto-loading via .ctx files ------------------------------------------

$Script:CtxAutoLoadDir = $null
$Script:CtxLastPwd = $null
# Tracks the "home:" directive override (issue #7), if any, from the last
# .ctx file auto-loaded, so Clear-CtxContext -All knows to look for the
# synthetic COPILOT_HOME at that location instead of the centralized one.
$Script:CtxAutoLoadHomeOverride = $null

function Get-CtxCopilotHomeRoot {
    if ($env:AI_CTX_PROFILES_SYNTHETIC_HOMES_ROOT) {
        return $env:AI_CTX_PROFILES_SYNTHETIC_HOMES_ROOT
    }
    return (Join-Path $HOME '.config\ctx\homes')
}

function Get-CtxCopilotDir {
    if ($env:CTX_COPILOT_DIR) {
        return $env:CTX_COPILOT_DIR
    }
    return (Join-Path $HOME '.copilot')
}

function Get-CtxSanitizedContextName {
    # Sanitizes a context name for safe use as a single path component.
    # '+' is already filesystem-safe and left as-is. Any other unsafe
    # character is replaced with '_' defensively.
    param([string]$Name)
    return ($Name -replace '[^A-Za-z0-9+._-]', '_')
}

# --- TOCTOU hardening (issue #17) ------------------------------------------
#
# Attacker model: a *different-user* process on a shared/multi-user machine
# that can write to some ancestor directory of a candidate COPILOT_HOME path
# swaps that ancestor for a symlink/junction/reparse point, or relaxes its
# ACL to grant itself write access, in the window between validation
# (Get-CtxValidatedHomePath) and the later filesystem operation (creating
# or recursively deleting the home directory). Explicitly OUT OF SCOPE:
# same-user races - a same-user attacker already runs with the same
# filesystem permissions ctx itself uses, so there is no privilege boundary
# to defend there.
#
# Mitigations:
#   1. Every existing ancestor component is checked for a reparse point
#      (symlink/junction) - unchanged from prior hardening (issue #16).
#   2. On Windows, every existing ancestor component's ACL is checked so
#      that only trusted principals - the current user (as owner) and the
#      well-known SYSTEM / built-in Administrators principals, resolved via
#      non-localized SIDs (WellKnownSidType) rather than display names, so
#      this works on non-English Windows installs - may hold write access.
#      An ordinary/unknown principal with write access to an ancestor could
#      perform the swap in (1) above, so such a path is rejected even
#      without an existing reparse point.
#   3. Callers (Set-CtxCopilotHome, Clear-CtxContext -All) re-invoke this
#      validation unconditionally, immediately before the filesystem
#      operation, rather than trusting the .ctx-parse-time check alone.
#      $Script:CtxToctouHook is a test-only seam (a no-op unless a test
#      assigns a scriptblock to it) used to deterministically arrange an
#      ancestor swap between the two checks; it does not run in normal
#      operation.
#
# Limitations: this narrows, but cannot eliminate, the race window between
# the final validation and the filesystem call - true atomicity would
# require OS-level primitives (e.g. O_NOFOLLOW-style openat semantics) that
# .NET/PowerShell do not expose portably. ACL validation failures fail
# closed (treated as unsafe) rather than silently proceeding.

$Script:CtxToctouHook = $null

function Invoke-CtxToctouHook {
    # Test-only seam: no-op in normal operation. Tests set
    # $Script:CtxToctouHook to a scriptblock that mutates the filesystem
    # (e.g. replacing an ancestor with a symlink) to deterministically
    # arrange a TOCTOU race between validation and use.
    if ($Script:CtxToctouHook) {
        & $Script:CtxToctouHook
    }
}

function Get-CtxTrustedAclSids {
    # Well-known, non-localized SIDs for principals that are always trusted
    # to legitimately hold write access to ancestor directories, so ordinary
    # Windows-inherited ACLs (which typically grant SYSTEM and built-in
    # Administrators full control) do not cause false-positive rejections.
    # Resolved via WellKnownSidType rather than name strings so this is
    # correct on non-English Windows installs.
    return @(
        (New-Object System.Security.Principal.SecurityIdentifier([System.Security.Principal.WellKnownSidType]::LocalSystemSid, $null)),
        (New-Object System.Security.Principal.SecurityIdentifier([System.Security.Principal.WellKnownSidType]::BuiltinAdministratorsSid, $null))
    )
}

function Test-CtxAncestorAclTrusted {
    # Windows-only: rejects (returns $false) if $Path's ACL grants write
    # access to any principal other than the current user, SYSTEM, or
    # built-in Administrators (see Get-CtxTrustedAclSids). Fails closed
    # (returns $false) if the ACL cannot be read at all. No-op ($true) on
    # non-Windows, where this ACL model does not apply - symlink/reparse
    # detection above is the cross-platform mitigation.
    param([string]$Path)
    if (-not ($IsWindows -or $env:OS -eq 'Windows_NT')) { return $true }
    try {
        $acl = Get-Acl -LiteralPath $Path -ErrorAction Stop
    } catch {
        return $false
    }
    $trusted = @(Get-CtxTrustedAclSids)
    $currentUserSid = $null
    try { $currentUserSid = [System.Security.Principal.WindowsIdentity]::GetCurrent().User } catch { }
    $writeRights = [System.Security.AccessControl.FileSystemRights]::Write -bor `
        [System.Security.AccessControl.FileSystemRights]::Modify -bor `
        [System.Security.AccessControl.FileSystemRights]::FullControl -bor `
        [System.Security.AccessControl.FileSystemRights]::CreateFiles -bor `
        [System.Security.AccessControl.FileSystemRights]::CreateDirectories -bor `
        [System.Security.AccessControl.FileSystemRights]::Delete
    foreach ($rule in $acl.Access) {
        if ($rule.AccessControlType -ne [System.Security.AccessControl.AccessControlType]::Allow) { continue }
        if (($rule.FileSystemRights -band $writeRights) -eq 0) { continue }
        $sid = $null
        try { $sid = $rule.IdentityReference.Translate([System.Security.Principal.SecurityIdentifier]) } catch { return $false }
        if ($currentUserSid -and $sid -eq $currentUserSid) { continue }
        $isTrusted = $false
        foreach ($t in $trusted) { if ($sid -eq $t) { $isTrusted = $true; break } }
        if (-not $isTrusted) { return $false }
    }
    return $true
}

function Get-CtxValidatedHomePath {
    param([string]$Path)
    if ([string]::IsNullOrWhiteSpace($Path) -or -not [System.IO.Path]::IsPathRooted($Path)) {
        throw "unsafe home: path must be absolute and non-empty"
    }
    $canonical = [System.IO.Path]::GetFullPath($Path)
    $roots = @($env:HOME, (Get-CtxCopilotHomeRoot)) | Where-Object { $_ }
    $allowed = $false
    $isAllowedRoot = $false
    foreach ($root in $roots) {
        $rootCanonical = [System.IO.Path]::GetFullPath($root).TrimEnd([System.IO.Path]::DirectorySeparatorChar, [System.IO.Path]::AltDirectorySeparatorChar)
        if ($canonical -eq $rootCanonical) { $isAllowedRoot = $true }
        if ($canonical -ne $rootCanonical -and $canonical.StartsWith($rootCanonical + [System.IO.Path]::DirectorySeparatorChar, [System.StringComparison]::OrdinalIgnoreCase)) { $allowed = $true }
    }
    if ($isAllowedRoot -or -not $allowed -or $canonical -eq [System.IO.Path]::GetPathRoot($canonical)) { throw "unsafe home: $Path is outside allowed roots or is a root" }
    $prefix = [System.IO.Path]::GetPathRoot($canonical)
    foreach ($part in ($canonical.Substring($prefix.Length) -split '[\\/]')) {
        if (-not $part) { continue }
        $prefix = Join-Path $prefix $part
        if (Test-Path -LiteralPath $prefix) {
            $item = Get-Item -LiteralPath $prefix -Force
            if ($item.LinkType -or ($item.Attributes -band [System.IO.FileAttributes]::ReparsePoint)) { throw "unsafe home: symlink or junction component in $Path" }
            if (-not (Test-CtxAncestorAclTrusted -Path $prefix)) { throw "unsafe home: untrusted writable ACL on ancestor component in $Path" }
        }
    }
    return $canonical
}

function Get-CtxCopilotHomeSharedFiles {
    # List of files symlinked/hardlinked back to the real ~/.copilot so
    # global auth/config/session history keep working identically across
    # all contexts. Also the authoritative list the reconciliation loop
    # walks on every activation to detect + repair a link that Copilot CLI
    # silently replaced with a plain file via rename(tmp, path) - the
    # confirmed hazard from plan section 3.4a.
    return @(
        'settings.json',
        'config.json',
        'mcp-config.json',
        'session-store.db',
        'session-store.db-shm',
        'session-store.db-wal'
    )
}

function Get-CtxCopilotHomeSharedDirs {
    # Directories linked back the same way (treated defensively with the
    # same reconciliation, even though only files were empirically
    # observed broken - see plan section 3.4a).
    return @('session-state', 'installed-plugins', 'logs')
}

function New-CtxLink {
    # Creates a link at $LinkPath pointing at $RealTarget, following the
    # Windows fallback ladder from plan section 3.5:
    #   1. Try a real symlink (New-Item -ItemType SymbolicLink) - requires
    #      Developer Mode or admin on Windows; works unprivileged on
    #      Linux/macOS pwsh.
    #   2. For directories, fall back to a junction (New-Item -ItemType
    #      Junction) - no special privilege required on Windows.
    #   3. For files, fall back to a hardlink (New-Item -ItemType
    #      HardLink) - requires the same volume, true for ~/.copilot and
    #      ~/.config/ctx both under $HOME by default.
    #   4. If all else fails, return $false so the caller can warn and
    #      leave COPILOT_HOME isolation off for this session rather than
    #      hard-failing ctx.
    param(
        [string]$LinkPath,
        [string]$RealTarget,
        [ValidateSet('file', 'dir')]
        [string]$Kind
    )

    try {
        New-Item -ItemType SymbolicLink -Path $LinkPath -Target $RealTarget -ErrorAction Stop | Out-Null
        return $true
    } catch {
        # Fall through to the next rung of the ladder.
    }

    if ($Kind -eq 'dir') {
        try {
            New-Item -ItemType Junction -Path $LinkPath -Target $RealTarget -ErrorAction Stop | Out-Null
            return $true
        } catch {
            # Fall through.
        }
    } else {
        try {
            New-Item -ItemType HardLink -Path $LinkPath -Target $RealTarget -ErrorAction Stop | Out-Null
            return $true
        } catch {
            # Fall through.
        }
    }

    return $false
}

function Get-CtxFileIdentity {
    param([string]$Path)
    if ($IsWindows -or $env:OS -eq 'Windows_NT') {
        try {
            if (-not ('CtxFileIdentity.Native' -as [type])) {
                Add-Type -TypeDefinition @'
using System;
using System.ComponentModel;
using System.Runtime.InteropServices;
using Microsoft.Win32.SafeHandles;
namespace CtxFileIdentity {
    public static class Native {
        [StructLayout(LayoutKind.Sequential)]
        public struct BY_HANDLE_FILE_INFORMATION {
            public uint FileAttributes, CreationTimeLow, CreationTimeHigh;
            public uint LastAccessTimeLow, LastAccessTimeHigh, LastWriteTimeLow, LastWriteTimeHigh;
            public uint VolumeSerialNumber, FileSizeHigh, FileSizeLow, NumberOfLinks, FileIndexHigh, FileIndexLow;
        }
        [DllImport("kernel32.dll", CharSet=CharSet.Unicode, SetLastError=true)]
        public static extern SafeFileHandle CreateFile(string name, uint access, uint share, IntPtr security, uint creation, uint flags, IntPtr template);
        [DllImport("kernel32.dll", SetLastError=true)]
        public static extern bool GetFileInformationByHandle(SafeFileHandle handle, out BY_HANDLE_FILE_INFORMATION info);
    }
}
'@
            }
            $handle = [CtxFileIdentity.Native]::CreateFile($Path, 0x80, 0x7, [IntPtr]::Zero, 3, 0x80, [IntPtr]::Zero)
            if ($handle -and -not $handle.IsInvalid) {
                $info = New-Object CtxFileIdentity.Native+BY_HANDLE_FILE_INFORMATION
                if ([CtxFileIdentity.Native]::GetFileInformationByHandle($handle, [ref]$info)) {
                    return "$($info.VolumeSerialNumber):$($info.FileIndexHigh):$($info.FileIndexLow)"
                }
            }
        } catch { }
        return $null
    }
    foreach ($statArgs in @(@('-c', '%d:%i'), @('-f', '%d:%i'))) {
        try {
            $value = (& stat @statArgs -- $Path 2>$null).Trim()
            if ($value) { return $value }
        } catch { }
    }
    return $null
}

function Test-CtxIsLink {
    param([string]$Path, [string]$Target)
    $item = Get-Item -LiteralPath $Path -Force -ErrorAction SilentlyContinue
    if (-not $item) { return $false }
    if ([bool]($item.LinkType) -or [bool]($item.Attributes -band [System.IO.FileAttributes]::ReparsePoint)) { return $true }
    if (-not $Target -and (Test-Path -LiteralPath $Path -PathType Leaf)) {
        try {
            $linkCount = (& stat -c '%h' -- $Path 2>$null).Trim()
            if ($linkCount -and [int]$linkCount -gt 1) { return $true }
        } catch { }
    }
    if ($Target -and (Test-Path -LiteralPath $Path -PathType Leaf) -and (Test-Path -LiteralPath $Target -PathType Leaf)) {
        $left = Get-CtxFileIdentity -Path $Path
        $right = Get-CtxFileIdentity -Path $Target
        return [bool]($left -and $right -and $left -eq $right)
    }
    return $false
}

function Get-CtxLinkTarget {
    param([string]$Path, [string]$Target)
    $item = Get-Item -LiteralPath $Path -Force
    if ($item.Target) { return @($item.Target)[0] }
    if ($Target -and (Test-CtxIsLink -Path $Path -Target $Target)) { return $Target }
    return $null
}

function Resolve-CtxLink {
    # Ensures $HomeDir\$Name is a link (symlink/junction/hardlink per the
    # fallback ladder) pointing at $RealTarget, self-healing the confirmed
    # rename()-through-symlink hazard (plan 3.4a): if Copilot CLI (or
    # anything else) replaced the link with a plain file/dir holding new
    # data, that data is copied back onto the real ~/.copilot target
    # *before* the link is recreated, so the most recent write is
    # preserved rather than silently lost. Returns $true on success.
    param(
        [string]$HomeDir,
        [string]$Name,
        [string]$RealTarget,
        [ValidateSet('file', 'dir')]
        [string]$Kind
    )

    $linkPath = Join-Path $HomeDir $Name

    $linkItem = Get-Item -LiteralPath $linkPath -Force -ErrorAction SilentlyContinue
    if ($linkItem) {
        if (Test-CtxIsLink -Path $linkPath -Target $RealTarget) {
            $currentTarget = Get-CtxLinkTarget -Path $linkPath -Target $RealTarget
            # Compare as raw strings (normalising separators) rather than via
            # Resolve-Path: when neither target exists yet (e.g. settings.json,
            # mcp-config.json not yet written by Copilot), Resolve-Path returns
            # $null for both sides and $null -eq $null is $true, which would
            # falsely treat a stale/wrong link as already correct and leave it
            # in place. A raw string compare mirrors ctx.sh's readlink check.
            $normalizedCurrent = if ($currentTarget) { $currentTarget.TrimEnd('\', '/').Replace('/', '\') } else { $null }
            $normalizedReal = $RealTarget.TrimEnd('\', '/').Replace('/', '\')
            if ($normalizedCurrent -and ($normalizedCurrent -eq $normalizedReal)) {
                # Already correct; no-op (idempotency, plan 3.4).
                return $true
            }
            Remove-Item -LiteralPath $linkPath -Force -Recurse -ErrorAction SilentlyContinue
        } else {
            # Not a link but exists: the confirmed hazard from 3.4a - the
            # CLI's write-tmp+rename() replaced our link with a real file
            # (or, defensively, a real dir) holding this context's latest
            # data. Copy it over the real target so the write is not
            # lost, then remove it and recreate the link.
            $parentOfTarget = Split-Path -Parent $RealTarget
            if ($parentOfTarget -and -not (Test-Path -LiteralPath $parentOfTarget)) {
                New-Item -ItemType Directory -Path $parentOfTarget -Force | Out-Null
            }
            if ($Kind -eq 'dir') {
                if (Test-Path -LiteralPath $RealTarget) {
                    Remove-Item -LiteralPath $RealTarget -Recurse -Force
                }
                Copy-Item -LiteralPath $linkPath -Destination $RealTarget -Recurse -Force
            } else {
                Copy-Item -LiteralPath $linkPath -Destination $RealTarget -Force
            }
            Remove-Item -LiteralPath $linkPath -Recurse -Force
        }
    }

    if (-not (Test-Path -LiteralPath $linkPath)) {
        $linkParent = Split-Path -Parent $linkPath
        if ($linkParent -and -not (Test-Path -LiteralPath $linkParent)) {
            New-Item -ItemType Directory -Path $linkParent -Force | Out-Null
        }
        if ($Kind -eq 'dir') {
            if (-not (Test-Path -LiteralPath $RealTarget)) {
                New-Item -ItemType Directory -Path $RealTarget -Force | Out-Null
            }
        } else {
            $targetParent = Split-Path -Parent $RealTarget
            if ($targetParent -and -not (Test-Path -LiteralPath $targetParent)) {
                New-Item -ItemType Directory -Path $targetParent -Force | Out-Null
            }
            if (-not (Test-Path -LiteralPath $RealTarget)) {
                New-Item -ItemType File -Path $RealTarget -Force | Out-Null
            }
        }
        if (-not (New-CtxLink -LinkPath $linkPath -RealTarget $RealTarget -Kind $Kind)) {
            Write-Warning "ctx: warning: could not create link $linkPath -> $RealTarget"
            return $false
        }
    }

    return $true
}

function Set-CtxCopilotHome {
    # Computes/reconciles the per-context COPILOT_HOME directory and
    # exports $env:COPILOT_HOME, mirroring _ctx_setup_copilot_home in
    # ctx.sh. $ContextName is the raw context name (e.g. "review+test");
    # $ResolvedDirs is the list of resolved directories for the active
    # context (profile dirs, or .ctx entries). $HomeOverride
    # is an absolute path (from the .ctx file's optional "home:" directive,
    # issue #7) or empty/$null to use the centralized default.
    param(
        [string]$ContextName,
        [string[]]$ResolvedDirs,
        [string]$HomeOverride
    )

    if ($HomeOverride) {
        $homeDir = $HomeOverride
    } else {
        $sanitized = Get-CtxSanitizedContextName -Name $ContextName
        $homesRoot = Get-CtxCopilotHomeRoot
        $homeDir = Join-Path $homesRoot $sanitized
    }
    $copilotDir = Get-CtxCopilotDir

    # TOCTOU hardening (issue #17): revalidate immediately before the
    # filesystem operation below, unconditionally (not only when $homeDir
    # is missing) - see the comment block above Get-CtxValidatedHomePath
    # for the attacker model and limitations. Invoke-CtxToctouHook is the
    # test-only seam used to deterministically arrange an ancestor swap
    # between the earlier .ctx-parse-time validation and this check.
    Invoke-CtxToctouHook
    try {
        $null = Get-CtxValidatedHomePath -Path $homeDir
    } catch {
        Write-Warning "ctx: warning: $_"
        return
    }

    if (-not (Test-Path -LiteralPath (Join-Path $homeDir 'skills'))) {
        try {
            New-Item -ItemType Directory -Path (Join-Path $homeDir 'skills') -Force -ErrorAction Stop | Out-Null
        } catch {
            Write-Warning "ctx: warning: could not create $homeDir; leaving COPILOT_HOME unset"
            return
        }
    }
    if (-not (Test-Path -LiteralPath $copilotDir)) {
        New-Item -ItemType Directory -Path $copilotDir -Force | Out-Null
    }

    $ok = $true
    foreach ($f in (Get-CtxCopilotHomeSharedFiles)) {
        if (-not (Resolve-CtxLink -HomeDir $homeDir -Name $f -RealTarget (Join-Path $copilotDir $f) -Kind 'file')) {
            $ok = $false
        }
    }
    foreach ($d in (Get-CtxCopilotHomeSharedDirs)) {
        if (-not (Resolve-CtxLink -HomeDir $homeDir -Name $d -RealTarget (Join-Path $copilotDir $d) -Kind 'dir')) {
            $ok = $false
        }
    }

    if (-not $ok) {
        Write-Warning "ctx: warning: one or more COPILOT_HOME links could not be created; leaving COPILOT_HOME unset for this session"
        return
    }

    # Reconcile skills/: desired (name -> target) pairs come from each
    # resolved dir's .github\skills subfolder, if present.
    $desiredSkills = @{}
    foreach ($rd in $ResolvedDirs) {
        $skillDir = Join-Path $rd '.github\skills'
        if (Test-Path -LiteralPath $skillDir -PathType Container) {
            Get-ChildItem -LiteralPath $skillDir -Directory | ForEach-Object {
                $desiredSkills[$_.Name] = $_.FullName
            }
        }
    }

    $skillsHome = Join-Path $homeDir 'skills'
    if (Test-Path -LiteralPath $skillsHome -PathType Container) {
        Get-ChildItem -LiteralPath $skillsHome -Force | ForEach-Object {
            if (-not $desiredSkills.ContainsKey($_.Name)) {
                Remove-Item -LiteralPath $_.FullName -Recurse -Force
            }
        }
    }

    foreach ($name in $desiredSkills.Keys) {
        $target = $desiredSkills[$name]
        $link = Join-Path $skillsHome $name
        $needsCreate = $true
        if (Test-Path -LiteralPath $link) {
            if ((Test-CtxIsLink -Path $link -Target $target) -and ((Get-CtxLinkTarget -Path $link -Target $target) -eq $target)) {
                $needsCreate = $false
            } else {
                Remove-Item -LiteralPath $link -Recurse -Force
            }
        }
        if ($needsCreate) {
            if (-not (New-CtxLink -LinkPath $link -RealTarget $target -Kind 'dir')) {
                Write-Warning "ctx: warning: could not create skill link $link -> $target"
            }
        }
    }

    $env:COPILOT_HOME = $homeDir
}

function Update-CtxSkillDirectories {
    # Merges the given skill directories into the "skillDirectories" array of
    # .github\copilot\settings.local.json, located under $BaseDir (the
    # directory containing the .ctx file). Creates the file (and any missing
    # parent directories) if it does not already exist. Preserves any other
    # keys, and any pre-existing skillDirectories entries, already in the file.
    param(
        [string]$BaseDir,
        [string[]]$SkillDirs
    )

    if (-not $SkillDirs -or $SkillDirs.Count -eq 0) {
        return
    }

    $settingsDir = Join-Path (Join-Path $BaseDir '.github') 'copilot'
    $settingsFile = Join-Path $settingsDir 'settings.local.json'

    $settings = $null
    if (Test-Path -LiteralPath $settingsFile -PathType Leaf) {
        try {
            $raw = Get-Content -LiteralPath $settingsFile -Raw
            if ($raw -and $raw.Trim()) {
                $settings = $raw | ConvertFrom-Json
            }
        } catch {
            Write-Warning "ctx: warning: could not parse $settingsFile ($_); it will be overwritten"
        }
    }

    if (-not $settings) {
        $settings = [PSCustomObject]@{}
    }

    $existing = @()
    if ($settings.PSObject.Properties.Match('skillDirectories').Count -gt 0 -and $settings.skillDirectories) {
        $existing = @($settings.skillDirectories)
    }

    $merged = @($existing + $SkillDirs | Select-Object -Unique)

    if ($settings.PSObject.Properties.Match('skillDirectories').Count -gt 0) {
        $settings.skillDirectories = $merged
    } else {
        $settings | Add-Member -MemberType NoteProperty -Name 'skillDirectories' -Value $merged
    }

    if (-not (Test-Path -LiteralPath $settingsDir -PathType Container)) {
        New-Item -ItemType Directory -Path $settingsDir -Force | Out-Null
    }

    ($settings | ConvertTo-Json -Depth 10) | Set-Content -LiteralPath $settingsFile -Encoding utf8
}

function Update-CtxWorkspaceFile {
    # Creates/updates a "<folder-name>.code-workspace" file next to the .ctx
    # file (under $BaseDir) so the project and its .ctx dependencies can be
    # browsed together in VS Code: this folder is added as "root: <name>",
    # and each .ctx entry is added as "ctx: <context-name>". Folders not
    # generated by ctx (i.e. not named "root: ..." / "ctx: ...") are left
    # untouched; other top-level keys (settings, extensions, ...) already in
    # the file are preserved.
    param(
        [string]$BaseDir,
        [string[]]$Names,
        [string[]]$Dirs
    )

    $resolvedBase = (Resolve-Path -LiteralPath $BaseDir).Path
    $folderName = Split-Path -Leaf $resolvedBase
    $workspaceFile = Join-Path $BaseDir "$folderName.code-workspace"

    $workspace = $null
    $workspaceExisted = Test-Path -LiteralPath $workspaceFile -PathType Leaf
    if ($workspaceExisted) {
        try {
            $raw = Get-Content -LiteralPath $workspaceFile -Raw
            if ($raw -and $raw.Trim()) {
                $workspace = $raw | ConvertFrom-Json
            }
        } catch {
            Write-Warning "ctx: warning: could not parse $workspaceFile ($_); it will be overwritten"
        }
    }

    if (-not $workspace) {
        $workspace = [PSCustomObject]@{}
    }

    $existingFolders = @()
    if ($workspace.PSObject.Properties.Match('folders').Count -gt 0 -and $workspace.folders) {
        $existingFolders = @($workspace.folders)
    }

    $userFolders = @($existingFolders | Where-Object {
        -not ($_.name -and ($_.name.ToString().StartsWith('root: ') -or $_.name.ToString().StartsWith('ctx: ')))
    })

    $rootEntry = [PSCustomObject]@{ path = '.'; name = "root: $folderName" }
    $ctxEntries = for ($i = 0; $i -lt $Names.Count; $i++) {
        [PSCustomObject]@{ path = $Dirs[$i]; name = "ctx: $($Names[$i])" }
    }

    $mergedFolders = @($rootEntry) + @($ctxEntries) + $userFolders

    if ($workspace.PSObject.Properties.Match('folders').Count -gt 0) {
        $workspace.folders = $mergedFolders
    } else {
        $workspace | Add-Member -MemberType NoteProperty -Name 'folders' -Value $mergedFolders
    }

    if ($workspace.PSObject.Properties.Match('settings').Count -eq 0) {
        $workspace | Add-Member -MemberType NoteProperty -Name 'settings' -Value ([PSCustomObject]@{})
    }

    if ($workspace.PSObject.Properties.Match('generatedBy').Count -eq 0 -and -not $workspaceExisted) {
        $workspace | Add-Member -MemberType NoteProperty -Name 'generatedBy' -Value 'ctx'
    }

    ($workspace | ConvertTo-Json -Depth 10) | Set-Content -LiteralPath $workspaceFile -Encoding utf8
}

function Find-CtxFile {
    $dir = (Get-Location).Path
    while ($true) {
        $candidate = Join-Path $dir '.ctx'
        if (Test-Path -LiteralPath $candidate -PathType Leaf) {
            return $candidate
        }
        $parent = Split-Path -Parent $dir
        if (-not $parent -or $parent -eq $dir) {
            break
        }
        $dir = $parent
    }
    return $null
}

function Parse-CtxFile {
    # Side-effect-free .ctx parser shared by Import-CtxFile and Test-CtxActivation.
    # It validates all labels/targets before either caller changes state.
    param([string]$CtxFile)
    $dirOfFile = Split-Path -Parent $CtxFile
    $names = @(); $dirs = @(); $seenLabels = @{}; $seenTargets = @{}; $homeOverride = $null
    foreach ($rawLine in Get-Content -LiteralPath $CtxFile) {
        $line = $rawLine.Trim()
        if (-not $line -or $line.StartsWith('#')) { continue }
        $sepIndex = $line.IndexOf(':')
        if ($sepIndex -lt 1) { throw "invalid .ctx line in $CtxFile (expected <name>:<path>): $line" }
        $name = $line.Substring(0, $sepIndex).Trim(); $path = $line.Substring($sepIndex + 1).Trim()
        if (-not $name -or -not $path) { throw "invalid .ctx line in $CtxFile (expected <name>:<path>): $line" }
        $labelKey = $name.ToLowerInvariant()
        if ($name -ine 'home') {
            if ($seenLabels.ContainsKey($labelKey)) { throw "duplicate .ctx entry label `"$name`"; first declared as `"$($seenLabels[$labelKey])`"" }
            $seenLabels[$labelKey] = $name
        }
        if ($path -ceq '@profile') { $resolvedPath = Resolve-CtxProfileIdentifier -Name $name }
        else { $resolvedPath = if ([System.IO.Path]::IsPathRooted($path)) { $path } else { Join-Path $dirOfFile $path } }
        if ($name -ieq 'home') {
            if ($homeOverride) { throw "duplicate `"home:`" directive in $CtxFile" }
            $homeOverride = Get-CtxValidatedHomePath -Path $resolvedPath
            continue
        }
        if (-not (Test-Path -LiteralPath $resolvedPath -PathType Container)) { throw ".ctx entry `"$name`" in $CtxFile points to missing directory: $resolvedPath" }
        $canonical = [System.IO.Path]::GetFullPath($resolvedPath)
        if ($seenTargets.ContainsKey($canonical)) { throw ".ctx entries `"$($seenTargets[$canonical])`" and `"$name`" resolve to the same directory" }
        $seenTargets[$canonical] = $name; $names += $name; $dirs += $resolvedPath
    }
    if ($names.Count -eq 0) { throw ".ctx file is empty or invalid: $CtxFile" }
    return [PSCustomObject]@{ Dir = $dirOfFile; Names = @($names); Dirs = @($dirs); HomeOverride = $homeOverride; Context = ($names -join '+') }
}

function Import-CtxFile {
    param([string]$CtxFile)
    try { $parsed = Parse-CtxFile -CtxFile $CtxFile } catch { Write-Error "ctx: error: $_"; return $false }
    Update-CtxWorkspaceFile -BaseDir $parsed.Dir -Names $parsed.Names -Dirs $parsed.Dirs
    $dirsCsv = $parsed.Dirs -join ','
    $env:COPILOT_CUSTOM_INSTRUCTIONS_DIRS = $dirsCsv
    $env:AI_CTX_PROFILES = $parsed.Context
    Set-CtxCopilotHome -ContextName $parsed.Context -ResolvedDirs $parsed.Dirs -HomeOverride $parsed.HomeOverride
    $Script:CtxAutoLoadHomeOverride = $parsed.HomeOverride
    $sharedCsv = ($parsed.Names | Select-Object -Skip 1) -join ', '
    Write-CtxStatus -ProfileName $parsed.Names[0] -SharedCsv $sharedCsv -DirsCsv $dirsCsv
    return $true
}
function Test-CtxActivation {
    # Read-only audit of the nearest .ctx activation. This function deliberately
    # does not call Import-CtxFile or Set-CtxCopilotHome.
    $ctxFile = Find-CtxFile
    if (-not $ctxFile) { Write-Host 'ctx check: no .ctx file found; nothing to check'; return $true }
    try { $parsed = Parse-CtxFile -CtxFile $ctxFile } catch { Write-Host 'CHECK FAIL parser: invalid .ctx file'; return $false }
    $dir = $parsed.Dir; $names = @($parsed.Names); $dirs = @($parsed.Dirs); $homeOverride = $parsed.HomeOverride; $failures = 0
    $expectedContext = $parsed.Context; $expectedDirs = $dirs -join ','
    if ($env:AI_CTX_PROFILES -ceq $expectedContext) { Write-Host 'CHECK PASS AI_CTX_PROFILES' } else { Write-Host "CHECK FAIL AI_CTX_PROFILES: expected $expectedContext, got $(if($env:AI_CTX_PROFILES){$env:AI_CTX_PROFILES}else{'<unset>'})"; $failures++ }
    if ($env:COPILOT_CUSTOM_INSTRUCTIONS_DIRS -ceq $expectedDirs) { Write-Host 'CHECK PASS COPILOT_CUSTOM_INSTRUCTIONS_DIRS' } else { Write-Host "CHECK FAIL COPILOT_CUSTOM_INSTRUCTIONS_DIRS: expected $expectedDirs, got $(if($env:COPILOT_CUSTOM_INSTRUCTIONS_DIRS){$env:COPILOT_CUSTOM_INSTRUCTIONS_DIRS}else{'<unset>'})"; $failures++ }
    $expectedHome = if ($homeOverride) { $homeOverride } else { Join-Path (Get-CtxCopilotHomeRoot) (Get-CtxSanitizedContextName -Name $expectedContext) }
    if ($env:COPILOT_HOME -ceq $expectedHome -and (Test-Path -LiteralPath $expectedHome -PathType Container)) { Write-Host 'CHECK PASS COPILOT_HOME' } else { Write-Host "CHECK FAIL COPILOT_HOME: expected $expectedHome, got $(if($env:COPILOT_HOME){$env:COPILOT_HOME}else{'<unset>'})"; $failures++ }
    foreach ($f in (Get-CtxCopilotHomeSharedFiles) + (Get-CtxCopilotHomeSharedDirs)) {
        $link = Join-Path $expectedHome $f; $target = Join-Path (Get-CtxCopilotDir) $f
        if ((Test-CtxIsLink -Path $link -Target $target) -and ((Get-CtxLinkTarget -Path $link -Target $target).TrimEnd('\','/') -eq $target.TrimEnd('\','/'))) { Write-Host "CHECK PASS link:$f" } else { Write-Host "CHECK FAIL link:${f}: expected link to $target"; $failures++ }
    }
    $desired = @{}
    foreach ($rd in $dirs) { $skillDir = Join-Path $rd '.github\skills'; if (Test-Path -LiteralPath $skillDir -PathType Container) { foreach ($s in Get-ChildItem -LiteralPath $skillDir -Directory | Sort-Object Name) { $desired[$s.Name] = $s.FullName } } }
    foreach ($name in ($desired.Keys | Sort-Object)) {
        $link = Join-Path $expectedHome "skills\$name"
        if ((Test-CtxIsLink -Path $link) -and ((Get-CtxLinkTarget -Path $link) -eq $desired[$name])) { Write-Host "CHECK PASS skill:$name" } else { Write-Host "CHECK FAIL skill:${name}: missing or wrong target"; $failures++ }
    }
    $actualSkillNames = @()
    $skillsHome = Join-Path $expectedHome 'skills'
    if (Test-Path -LiteralPath $skillsHome -PathType Container) {
        $actualSkillNames = @(Get-ChildItem -LiteralPath $skillsHome -Force | Sort-Object Name | Select-Object -ExpandProperty Name)
    }
    foreach ($actualName in $actualSkillNames) {
        if (-not $desired.ContainsKey($actualName)) {
            Write-Host "CHECK FAIL skill:${actualName}: unexpected skill"
            $failures++
        }
    }
    Write-Host 'CHECK SKIP skills: copilot probe disabled in read-only check'
    $workspace = Join-Path $dir "$(Split-Path -Leaf $dir).code-workspace"
    if (Test-Path -LiteralPath $workspace -PathType Leaf) {
        try {
            $w = Get-Content -LiteralPath $workspace -Raw | ConvertFrom-Json
            $pairs = @($w.folders | ForEach-Object { "$($_.path)`n$($_.name)" })
            $rootName = "root: $(Split-Path -Leaf $dir)"
            $ok = $pairs -contains ".`n$rootName"
            for ($j=0; $j -lt $names.Count; $j++) { if ($pairs -notcontains "$($dirs[$j])`nctx: $($names[$j])") { $ok = $false } }
            $marker = if ($w.generatedBy -ceq 'ctx') { 'ctx' } else { 'unmarked' }
            Write-Host "CHECK PASS workspace marker=$marker"
            if (-not $ok) { Write-Host 'CHECK FAIL workspace: missing expected folder(s)'; $failures++ }
        } catch { Write-Host 'CHECK FAIL workspace: invalid JSON'; $failures++ }
    } else { Write-Host 'CHECK SKIP workspace: no adjacent workspace file' }
    if ($failures -eq 0) { Write-Host 'ctx check: PASS'; return $true }
    Write-Host "ctx check: FAIL ($failures)"; return $false
}

function Invoke-CtxAutoLoad {
    if ($env:CTX_AUTO_LOAD -eq '0') {
        return
    }

    $ctxFile = Find-CtxFile
    if ($ctxFile) {
        $dirOfFile = Split-Path -Parent $ctxFile
        if ($Script:CtxAutoLoadDir -ne $dirOfFile) {
            if (Import-CtxFile -CtxFile $ctxFile) {
                $Script:CtxAutoLoadDir = $dirOfFile
            }
        }
    } else {
        if ($Script:CtxAutoLoadDir) {
            Clear-CtxContext
            $Script:CtxAutoLoadDir = $null
        }
    }
}

function Invoke-CtxChpwdHook {
    $current = (Get-Location).Path
    if ($Script:CtxLastPwd -ne $current) {
        $Script:CtxLastPwd = $current
        Invoke-CtxAutoLoad
    }
}

# Wrap the existing prompt function (if any, e.g. Oh My Posh's) so the
# directory-change hook fires on every prompt render without clobbering
# whatever prompt customization is already in place.
if (-not $Script:CtxOriginalPrompt) {
    $Script:CtxOriginalPrompt = $function:prompt
}

function prompt {
    Invoke-CtxChpwdHook
    if ($Script:CtxOriginalPrompt) {
        & $Script:CtxOriginalPrompt
    } else {
        "PS $($executionContext.SessionState.Path.CurrentLocation)$('>' * ($nestedPromptLevel + 1)) "
    }
}

# Run once for the shell's starting directory.
$Script:CtxLastPwd = (Get-Location).Path
Invoke-CtxAutoLoad

# --- Tab completion --------------------------------------------------------

function Get-CtxSubdirName {
    param([string]$Base)
    if (Test-Path -LiteralPath $Base -PathType Container) {
        Get-ChildItem -LiteralPath $Base -Directory | Select-Object -ExpandProperty Name
    }
}

Register-ArgumentCompleter -CommandName ctx -ScriptBlock {
    param($wordToComplete, $commandAst)

    $root = Get-CtxRoot
    $elements = $commandAst.CommandElements
    # elements[0] is 'ctx' itself; count how many positional args precede current one.
    $argIndex = $elements.Count - 1

    if ($argIndex -le 1) {
        $candidates = @('current', 'clear') + (Get-CtxSubdirName (Join-Path $root 'profiles'))
    } elseif ($argIndex -eq 2 -and $elements[1].Extent.Text -eq 'clear') {
        $candidates = @('--all')
    } else {
        $candidates = Get-CtxSubdirName (Join-Path $root 'profiles')
    }

    $candidates |
        Where-Object { $_ -like "$wordToComplete*" } |
        Sort-Object -Unique |
        ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_) }
}
