#!/usr/bin/env bash
# shellcheck shell=bash
#
# ctx.sh - Portable context switcher for GitHub Copilot CLI
# ==========================================================
#
# Composes AI agent configuration directories (profiles)
# stored under a root directory (default: ~/work/ai-config) into the
# COPILOT_CUSTOM_INSTRUCTIONS_DIRS environment variable, for the current
# shell session.
#
# Compatible with bash and zsh.
#
# ---------------------------------------------------------------------------
# INSTALLATION
# ---------------------------------------------------------------------------
#   1. Copy (or symlink) this file to ~/.config/ctx/ctx.sh
#        mkdir -p ~/.config/ctx
#        cp ctx.sh ~/.config/ctx/ctx.sh
#      (or run ./install.sh from this repo)
#
#   2. zsh setup - add to ~/.zshrc:
#        source "$HOME/.config/ctx/ctx.sh"
#
#   3. bash setup - add to ~/.bashrc:
#        source "$HOME/.config/ctx/ctx.sh"
#
#   4. Completion is registered automatically when this file is sourced.
#
# ---------------------------------------------------------------------------
# DIRECTORY LAYOUT EXPECTED
# ---------------------------------------------------------------------------
#   ${AI_CTX_PROFILES_CONFIG_ROOT:-$HOME/work/ai-config}/
#   └── profiles/
#       ├── review/
#       ├── architecture/
#       ├── incident/
#       ├── coding/
#       ├── dotnet/
#       ├── azure/
#       ├── terraform/
#       └── security/
#
# ---------------------------------------------------------------------------
# USAGE
# ---------------------------------------------------------------------------
#   ctx review                    # activate the "review" profile
#   ctx coding azure              # activate multiple profiles
#   ctx review dotnet security    # activate multiple profiles
#   ctx current                   # show active profiles/env vars
#   ctx clear                     # unset AI_CTX_PROFILES / COPILOT_CUSTOM_INSTRUCTIONS_DIRS / COPILOT_HOME
#   ctx clear --all               # remove the current context home and owned workspace artifacts
#   ctx --help                    # usage help
#
# --- AUTO-LOADING (.ctx files) -----------------------------------------
#   Drop a ".ctx" file in any project directory. Each non-empty, non-comment
#   line maps an arbitrary context name to a custom-instructions directory:
#
#       <context-name>:<path-to-folder>
#
#   Example:
#       review:/home/user/work/ai-config/profiles/review
#       dotnet:/home/user/work/ai-config/profiles/dotnet
#       security:./local-instructions
#
#   Relative paths are resolved against the directory containing the .ctx
#   file (not the current working directory). Unlike `ctx <profile> [profile...]`,
#   these names are NOT looked up under AI_CTX_PROFILES_CONFIG_ROOT/profiles - the
#   path on each line is used directly. Every path is validated to exist.
#
#   When your prompt renders after a `cd` into that directory (or a
#   descendant of it), AI_CTX_PROFILES and COPILOT_CUSTOM_INSTRUCTIONS_DIRS are
#   set (overwriting any previous value) from the file's contents. Leaving
#   the directory tree (into a location with no .ctx file) automatically
#   clears the context.
#
#   NOAUTOLOAD FLAG
#   ----------------
#   Add a bare "noautoload" line (no colon, case-insensitive) to the .ctx
#   file to prevent the directory-change hook from loading it automatically:
#
#       noautoload
#       review:/home/user/work/ai-config/profiles/review
#
#   The file remains valid and can be loaded explicitly at any time with
#   "ctx load <path-to-.ctx-file>" (see below).
#
#   SKILL DISCOVERY
#   ----------------
#   COPILOT_CUSTOM_INSTRUCTIONS_DIRS does not make Copilot CLI discover agent
#   skills stored in your .ctx entries. ctx sets COPILOT_HOME to a per-context
#   home and links the resolved .github/skills entries into its skills folder.
#   Shared Copilot files are reconciled against the real Copilot home on every
#   activation. The cache remains after ctx clear; ctx clear --all removes it.
#
#   VS CODE WORKSPACE
#   ------------------
#   Whenever a .ctx file is loaded, a multi-root VS Code workspace file
#   named "<folder-name>.code-workspace" is created (or updated, requires
#   python3) next to it, so the project and its .ctx dependencies can all be
#   browsed in one VS Code window:
#
#     - This folder is added as "root: <folder-name>".
#     - Each .ctx entry is added as "ctx: <context-name>", pointing at the
#       resolved directory from that line.
#
#   Any other folders already present in the workspace file (added by you,
#   or by VS Code) are preserved; only entries previously generated by ctx
#   (named "root: ..." or "ctx: ...") are replaced on each load. Nothing is
#   removed from the workspace file when the context is cleared (run
#   "ctx clear --all" to delete it instead).
#
#   Disable this behavior for the session with:
#       export CTX_AUTO_LOAD=0
#
# ---------------------------------------------------------------------------

# --- Core implementation -----------------------------------------------

_ctx_root() {
    printf '%s\n' "${AI_CTX_PROFILES_CONFIG_ROOT:-$HOME/work/ai-config}"
}

# Lowercase a context name without shell-specific case conversion syntax.
# `${name,,}` is not supported by zsh, despite ctx.sh supporting both shells.
_ctx_lowercase() {
    printf '%s\n' "$1" | tr '[:upper:]' '[:lower:]'
}

_ctx_usage() {
    cat <<'EOF'
Usage:
  ctx <profile> [profile...]  Activate one or more profiles
  ctx current                   Show the currently active context
  ctx check                    Read-only audit against the nearest .ctx file
  ctx clear                   Clear the currently active context
  ctx clear --all             Remove the current context home and generated
                               project artifacts next to the nearest .ctx file
                               Workspace files are removed only with the exact
                               generatedBy: "ctx" marker; unmarked, invalid,
                               and linked workspaces are preserved with a warning.
  ctx load <file>             Explicitly load a .ctx file (bypasses noautoload)
  ctx --help | -h             Show this help message

Examples:
  ctx review
  ctx coding azure
  ctx review dotnet security
  ctx load /path/to/project/.ctx

Environment:
  AI_CTX_PROFILES_CONFIG_ROOT      Root directory containing profiles/
                       (default: $HOME/work/ai-config)
  CTX_AUTO_LOAD        Set to 0 to disable automatic .ctx loading on cd
EOF
}

_ctx_print_status() {
    local profile="$1"
    local shared_csv="$2"
    local dirs_csv="$3"

    printf '\n[AI Context]\n\n'
    printf 'Profile : %s\n' "${profile:-<none>}"
    printf 'Profiles: %s\n' "${shared_csv:-<none>}"
    printf '\nAI_CTX_PROFILES=%s\n' "${AI_CTX_PROFILES:-<unset>}"
    printf 'COPILOT_HOME=%s\n' "${COPILOT_HOME:-<unset>}"
    printf '\nCOPILOT_CUSTOM_INSTRUCTIONS_DIRS=\n'
    if [ -n "$dirs_csv" ]; then
        printf '%s\n' "$dirs_csv" | tr ',' '\n'
    else
        printf '<unset>\n'
    fi
}

_ctx_current() {
    if [ -z "${AI_CTX_PROFILES:-}" ]; then
        printf 'No active AI context.\n'
        printf 'Run "ctx <profile> [profile...]" to activate one.\n'
        return 0
    fi

    local profile shared_csv
    profile="${AI_CTX_PROFILES%%+*}"
    if [ "$AI_CTX_PROFILES" = "$profile" ]; then
        shared_csv=""
    else
        shared_csv="${AI_CTX_PROFILES#*+}"
        shared_csv="${shared_csv//+/, }"
    fi

    _ctx_print_status "$profile" "$shared_csv" "${COPILOT_CUSTOM_INSTRUCTIONS_DIRS:-}"
}

_ctx_file_identity() {
    local path="$1" result
    if command -v stat >/dev/null 2>&1; then
        result="$(stat -c '%d:%i' -- "$path" 2>/dev/null)" || result=""
        # BSD/macOS stat does not accept GNU's `--` option separator.
        [ -n "$result" ] || result="$(stat -f '%d:%i' "$path" 2>/dev/null)"
    fi
    [ -n "$result" ] || return 1
    printf '%s\n' "$result"
}

_ctx_link_matches() {
    local link="$1" target="$2" link_target
    if [ -L "$link" ]; then
        link_target="$(readlink "$link")"
        [ "$link_target" = "$target" ]
        return
    fi
    [ -f "$link" ] && [ -f "$target" ] || return 1
    [ "$(_ctx_file_identity "$link")" = "$(_ctx_file_identity "$target")" ]
}

_ctx_workspace_is_generated() {
    local workspace_file="$1" python_bin=""
    if command -v python3 >/dev/null 2>&1; then
        python_bin="python3"
    elif command -v python >/dev/null 2>&1; then
        python_bin="python"
    else
        return 1
    fi
    "$python_bin" - "$workspace_file" <<'PYEOF'
import json
import sys

try:
    with open(sys.argv[1], "r", encoding="utf-8") as f:
        workspace = json.load(f)
except (OSError, ValueError):
    sys.exit(1)
sys.exit(0 if isinstance(workspace, dict) and workspace.get("generatedBy") == "ctx" else 1)
PYEOF
}

_ctx_clear() {
    # $1: optional "--all" to also delete the artifacts ctx generates next
    # to the nearest .ctx file (.github/copilot/settings.local.json and the
    # "<folder-name>.code-workspace" file), instead of just leaving them in
    # place for next time.
    local prev_context="${AI_CTX_PROFILES:-}"
    local prev_home="${COPILOT_HOME:-}"
    local cleanup_status=0
    unset AI_CTX_PROFILES
    unset COPILOT_CUSTOM_INSTRUCTIONS_DIRS
    unset COPILOT_HOME

    if [ "${1:-}" = "--all" ]; then
        local dir_of_file="$_ctx_auto_load_dir"
        if [ -z "$dir_of_file" ]; then
            local ctx_file
            if ctx_file="$(_ctx_find_ctx_file)"; then
                dir_of_file="$(dirname "$ctx_file")"
            fi
        fi

        if [ -n "$dir_of_file" ]; then
            local settings_file="$dir_of_file/.github/copilot/settings.local.json"
            if [ -f "$settings_file" ]; then
                # Legacy cleanup: settings.local.json's skillDirectories is
                # confirmed inert (issue #1) and no longer written by ctx,
                # but pre-existing files from older ctx versions are still
                # removed here for one release. Safe to drop this block in
                # a future release once users have upgraded.
                if rm -f "$settings_file"; then
                    printf 'ctx: removed %s\n' "$settings_file"
                else
                    cleanup_status=$?
                    printf 'ctx: error: failed to remove %s (status %s)\n' "$settings_file" "$cleanup_status" >&2
                fi
            fi

            local folder_name workspace_file
            folder_name="$(basename "$dir_of_file")"
            workspace_file="$dir_of_file/$folder_name.code-workspace"
            if [ -L "$workspace_file" ]; then
                printf 'ctx: preserved linked workspace %s\n' "$workspace_file" >&2
            elif [ -f "$workspace_file" ]; then
                if _ctx_workspace_is_generated "$workspace_file"; then
                    if rm -f "$workspace_file"; then
                        printf 'ctx: removed %s\n' "$workspace_file"
                    else
                        cleanup_status=$?
                        printf 'ctx: error: failed to remove %s (status %s)\n' "$workspace_file" "$cleanup_status" >&2
                    fi
                else
                    printf 'ctx: preserved unowned workspace %s\n' "$workspace_file" >&2
                fi
            fi
        else
            if [ -n "$prev_context" ]; then
                # Context was activated manually (no .ctx file), so there are
                # no on-disk artifacts (settings.local.json / workspace file)
                # to clean up, but the COPILOT_HOME directory below still
                # gets removed - don't imply nothing happens at all.
                printf 'ctx: warning: no .ctx file found; skipping artifact cleanup\n' >&2
            else
                printf 'ctx: warning: no .ctx file found; nothing to remove\n' >&2
            fi
        fi

        if [ -n "$prev_context" ]; then
            local sanitized homes_root home_dir
            if [ -n "$_ctx_auto_load_home_override" ]; then
                home_dir="$_ctx_auto_load_home_override"
            else
                sanitized="$(_ctx_sanitize_context_name "$prev_context")"
                homes_root="$(_ctx_copilot_home_root)"
                home_dir="$homes_root/$sanitized"
            fi
            if [ -z "$prev_home" ] || [ "$home_dir" != "$prev_home" ] || ! _ctx_validate_home_path "$home_dir" >/dev/null; then
                printf 'ctx: error: refusing to remove unsafe or unselected home: %s\n' "$home_dir" >&2
                return 1
            fi
            if [ -d "$home_dir" ] && [ ! -L "$home_dir" ]; then
                local remove_status=0
                rm -rf -- "$home_dir" || remove_status=$?
                if [ "$remove_status" -ne 0 ]; then
                    printf 'ctx: error: failed to remove %s (status %s)\n' "$home_dir" "$remove_status" >&2
                    return "$remove_status"
                fi
                printf 'ctx: removed %s\n' "$home_dir"
            fi
        fi
    fi

    export CTX_AUTO_LOAD_DIR=""
    _ctx_auto_load_dir=""
    _ctx_auto_load_home_override=""
    printf 'AI context cleared.\n'
    return "$cleanup_status"
}

_ctx_resolve_profile_identifier() {
    # Resolve a profile identifier only if its canonical target is an immediate
    # descendant of the canonical profiles root. This rejects traversal and
    # profile-root symlinks that escape the configured profiles directory.
    local name="$1" profiles_root root_canonical candidate canonical
    case "$name" in
        ''|.|..|*/*|*\\*)
            printf 'ctx: error: invalid profile identifier "%s"\n' "$name" >&2
            return 1 ;;
    esac
    profiles_root="$(_ctx_root)/profiles"
    root_canonical="$(realpath -m -- "$profiles_root" 2>/dev/null)" || return 1
    candidate="$profiles_root/$name"
    if [ ! -d "$candidate" ]; then
        printf 'ctx: error: unknown profile "%s" (looked in %s)\n' "$name" "$profiles_root" >&2
        printf 'ctx: available profiles:\n' >&2
        [ -d "$profiles_root" ] && find "$profiles_root" -mindepth 1 -maxdepth 1 -type d -exec basename {} \; 2>/dev/null | sed 's/^/  - /' >&2
        return 1
    fi
    canonical="$(realpath -m -- "$candidate" 2>/dev/null)" || return 1
    if [ "$(dirname "$canonical")" != "$root_canonical" ]; then
        printf 'ctx: error: invalid profile identifier "%s"\n' "$name" >&2
        return 1
    fi
    printf '%s\n' "$canonical"
}

ctx() {
    if [ "$#" -eq 0 ]; then _ctx_usage; return 0; fi
    case "$1" in
        -h|--help) _ctx_usage; return 0 ;;
        current) _ctx_current; return 0 ;;
        check) _ctx_check; return $? ;;
        clear) _ctx_clear "$2"; return $? ;;
        load)
            if [ -z "${2:-}" ]; then
                printf 'ctx: error: "ctx load" requires a path argument\n' >&2
                printf 'Usage: ctx load <path-to-.ctx-file>\n' >&2
                return 1
            fi
            local load_file load_dir
            case "$2" in
                /*) load_file="$2" ;;
                *) load_file="$PWD/$2" ;;
            esac
            if [ ! -f "$load_file" ]; then
                printf 'ctx: error: file not found: %s\n' "$load_file" >&2
                return 1
            fi
            load_dir="$(dirname "$load_file")"
            if _ctx_load_ctx_file "$load_file"; then
                _ctx_auto_load_dir="$load_dir"
            else
                return $?
            fi
            return 0
            ;;
    esac

    local root profile_name profile_dir context_name context_lc profile_name_lc
    root="$(_ctx_root)"
    if [ ! -d "$root" ]; then printf 'ctx: error: AI config root does not exist: %s\n' "$root" >&2; return 1; fi
    local dirs_csv=""
    local -a resolved_dirs_manual=() context_names=() seen_names=()
    for context_name in "$@"; do
        context_lc="$(_ctx_lowercase "$context_name")"
        for profile_name_lc in "${seen_names[@]}"; do
            if [ "$profile_name_lc" = "$context_lc" ]; then printf 'ctx: error: duplicate profile "%s"\n' "$context_name" >&2; return 1; fi
        done
        seen_names+=("$context_lc")
        if ! profile_dir="$(_ctx_resolve_profile_identifier "$context_name")"; then return 1; fi
        context_names+=("$context_name"); resolved_dirs_manual+=("$profile_dir")
        [ -z "$dirs_csv" ] && dirs_csv="$profile_dir" || dirs_csv="$dirs_csv,$profile_dir"
    done
    [ "${#context_names[@]}" -gt 0 ] || return 1
    profile_name="${context_names[0]}"
    AI_CTX_PROFILES="${context_names[*]}"; AI_CTX_PROFILES="${AI_CTX_PROFILES// /+}"
    if ! _ctx_setup_copilot_home "$AI_CTX_PROFILES" "" "${resolved_dirs_manual[@]}"; then return 1; fi
    export COPILOT_CUSTOM_INSTRUCTIONS_DIRS="$dirs_csv" AI_CTX_PROFILES
    _ctx_print_status "$AI_CTX_PROFILES" "" "$dirs_csv"
}
# --- Auto-loading via .ctx files ----------------------------------------

_ctx_auto_load_dir=""
# Tracks the "home:" directive override (issue #7), if any, from the last
# .ctx file auto-loaded, so _ctx_clear --all knows to look for the
# synthetic COPILOT_HOME at that location instead of the centralized one.
_ctx_auto_load_home_override=""

_ctx_ctx_file_has_noautoload() {
    # Returns 0 (true) when the given .ctx file contains a bare "noautoload"
    # directive (case-insensitive). Deliberately independent of
    # _ctx_parse_ctx_file (which fully validates the file and can fail) so
    # the auto-load hook can always honor the flag even on an otherwise
    # invalid .ctx file.
    local ctx_file="$1"
    local line
    while IFS= read -r line || [ -n "$line" ]; do
        line="${line%$'\r'}"
        case "$(_ctx_lowercase "$line")" in
            noautoload) return 0 ;;
        esac
    done < "$ctx_file"
    return 1
}

_ctx_find_ctx_file() {
    # Search from $PWD upward to the filesystem root for a ".ctx" file.
    local dir="$PWD"
    while [ -n "$dir" ]; do
        if [ -f "$dir/.ctx" ]; then
            printf '%s\n' "$dir/.ctx"
            return 0
        fi
        [ "$dir" = "/" ] && break
        dir="$(dirname "$dir")"
    done
    return 1
}

_ctx_auto_load_hook() {
    [ "${CTX_AUTO_LOAD:-1}" = "0" ] && return 0

    local ctx_file
    if ctx_file="$(_ctx_find_ctx_file)"; then
        local dir_of_file
        dir_of_file="$(dirname "$ctx_file")"
        if _ctx_ctx_file_has_noautoload "$ctx_file"; then
            # File explicitly opts out of auto-loading. If we previously
            # had this file loaded (e.g. flag was added after loading),
            # clear it now and forget the directory so we don't linger.
            if [ "$_ctx_auto_load_dir" = "$dir_of_file" ]; then
                _ctx_clear
                _ctx_auto_load_dir=""
            fi
            return 0
        fi
        if [ "$_ctx_auto_load_dir" != "$dir_of_file" ]; then
            if _ctx_load_ctx_file "$ctx_file"; then
                _ctx_auto_load_dir="$dir_of_file"
            fi
        fi
    else
        if [ -n "$_ctx_auto_load_dir" ]; then
            _ctx_clear
            _ctx_auto_load_dir=""
        fi
    fi
}

_ctx_copilot_home_root() {
    printf '%s\n' "${AI_CTX_PROFILES_CONFIG_ROOT:+}" >/dev/null # no-op, keeps shellcheck quiet about unused pattern
    printf '%s\n' "${AI_CTX_PROFILES_SYNTHETIC_HOMES_ROOT:-$HOME/.config/ctx/homes}"
}

_ctx_sanitize_context_name() {
    # Sanitizes a context name for safe use as a single path component.
    # '+' is already filesystem-safe and left as-is. Any '/' or other
    # unsafe character is replaced with '_' defensively.
    local name="$1"
    printf '%s' "$name" | tr -c 'A-Za-z0-9+._-' '_'
}

_ctx_validate_home_path() {
    # Print the canonical, safe path. Custom homes may only be descendants
    # of HOME or AI_CTX_PROFILES_SYNTHETIC_HOMES_ROOT; existing symlink components are forbidden.
    local candidate="$1" canonical root root_canonical part prefix rest
    [ -n "$candidate" ] || { printf 'ctx: error: unsafe home: empty path\n' >&2; return 1; }
    case "$candidate" in /*) ;; *) printf 'ctx: error: unsafe home: path is not absolute: %s\n' "$candidate" >&2; return 1 ;; esac
    canonical="$(realpath -m -- "$candidate" 2>/dev/null)" || { printf 'ctx: error: unsafe home: %s\n' "$candidate" >&2; return 1; }
    [ "$canonical" != "/" ] || { printf 'ctx: error: unsafe home: filesystem root\n' >&2; return 1; }
    local allowed=1 root_is_candidate=0
    for root in "$HOME" "${AI_CTX_PROFILES_SYNTHETIC_HOMES_ROOT:-}"; do
        [ -n "$root" ] || continue
        root_canonical="$(realpath -m -- "$root" 2>/dev/null)" || continue
        if [ "$canonical" = "$root_canonical" ]; then root_is_candidate=1; fi
        if [ "$canonical" != "$root_canonical" ] && [[ "$canonical" == "$root_canonical"/* ]]; then allowed=0; fi
    done
    [ "$root_is_candidate" -eq 0 ] || { printf 'ctx: error: unsafe home: %s is an allowed root, not a descendant\n' "$candidate" >&2; return 1; }
    [ "$allowed" -eq 0 ] || { printf 'ctx: error: unsafe home: %s is outside HOME/AI_CTX_PROFILES_SYNTHETIC_HOMES_ROOT\n' "$candidate" >&2; return 1; }
    rest="${candidate#/}"; prefix="/"
    while [ -n "$rest" ]; do
        part="${rest%%/*}"
        if [ "$rest" = "$part" ]; then rest=""; else rest="${rest#*/}"; fi
        [ -n "$part" ] || continue
        prefix="${prefix%/}/$part"
        [ ! -L "$prefix" ] || { printf 'ctx: error: unsafe home: symlink component in %s\n' "$candidate" >&2; return 1; }
    done
    printf '%s\n' "$canonical"
}

# List of files
# symlinked back to the real ~/.copilot so global auth/config/session
# history keep working identically across all contexts. This is also the
# authoritative list the 3.4a reconciliation loop walks on every
# activation to detect + repair a symlink that Copilot CLI silently
# replaced with a plain file via rename(tmp, path).
_ctx_copilot_home_shared_files() {
    cat <<'EOF'
settings.json
config.json
mcp-config.json
session-store.db
session-store.db-shm
session-store.db-wal
EOF
}

# Directories symlinked back to the real ~/.copilot the same way (treated
# defensively with the same reconciliation, even though only files were
# empirically observed broken - see plan section 3.4a).
_ctx_copilot_home_shared_dirs() {
    cat <<'EOF'
session-state
installed-plugins
logs
EOF
}

_ctx_reconcile_symlink() {
    # Ensures $home_dir/$name is a symlink pointing at $real_target,
    # self-healing the confirmed rename()-through-symlink hazard (plan
    # 3.4a): if Copilot CLI (or anything else) replaced the symlink with
    # a plain file/dir holding new data, that data is copied back onto
    # the real ~/.copilot target *before* the symlink is recreated, so
    # the most recent write is preserved rather than silently lost.
    #
    # $1: home_dir   $2: name (relative path under home_dir)
    # $3: real_target (absolute path under ~/.copilot)
    # $4: kind - "file" or "dir"
    local home_dir="$1" name="$2" real_target="$3" kind="$4"
    local link_path="$home_dir/$name"

    if [ -L "$link_path" ]; then
        local current_target
        current_target="$(readlink "$link_path")"
        if [ "$current_target" = "$real_target" ]; then
            # Already correct; no-op (idempotency, plan 3.4).
            return 0
        fi
        # Stale/incorrect symlink target - remove and recreate below.
        rm -f "$link_path"
    elif [ -e "$link_path" ]; then
        # Not a symlink but exists: the confirmed hazard from 3.4a - the
        # CLI's write-tmp+rename() replaced our symlink with a real file
        # (or, defensively, a real dir) holding this context's latest
        # data. Copy it over the real target so the write is not lost,
        # then remove it and recreate the symlink.
        mkdir -p "$(dirname "$real_target")"
        if [ "$kind" = "dir" ]; then
            rm -rf "$real_target"
            cp -a "$link_path" "$real_target"
            rm -rf "$link_path"
        else
            cp -f "$link_path" "$real_target"
            rm -f "$link_path"
        fi
    fi

    if [ ! -e "$link_path" ]; then
        mkdir -p "$(dirname "$link_path")"
        if [ "$kind" = "dir" ]; then
            mkdir -p "$real_target"
        else
            mkdir -p "$(dirname "$real_target")"
            [ -e "$real_target" ] || : > "$real_target"
        fi
        if ! ln -s "$real_target" "$link_path" 2>/dev/null; then
            printf 'ctx: warning: could not create symlink %s -> %s\n' "$link_path" "$real_target" >&2
            return 1
        fi
    fi
    return 0
}

_ctx_setup_copilot_home() {
    # $1: context-name (raw, e.g. "review+test")
    # $2: home-dir override (absolute path) or "" to use the centralized
    #     default. Set via the .ctx file's optional "home:<path>" directive
    #     (issue #7); manual "ctx <profile>..." invocations always pass "".
    # remaining args: resolved directories for the active context
    local context_name="$1"
    local home_override="$2"
    shift 2
    local -a resolved_dirs=("$@")

    local sanitized homes_root home_dir copilot_dir
    if [ -n "$home_override" ]; then
        home_dir="$home_override"
    else
        sanitized="$(_ctx_sanitize_context_name "$context_name")"
        homes_root="$(_ctx_copilot_home_root)"
        home_dir="$homes_root/$sanitized"
    fi
    copilot_dir="${CTX_COPILOT_DIR:-$HOME/.copilot}"

    mkdir -p "$home_dir/skills" || {
        printf 'ctx: warning: could not create %s; leaving COPILOT_HOME unset\n' "$home_dir" >&2
        return 1
    }
    mkdir -p "$copilot_dir" 2>/dev/null || true

    local ok=1
    local f
    while IFS= read -r f; do
        [ -z "$f" ] && continue
        _ctx_reconcile_symlink "$home_dir" "$f" "$copilot_dir/$f" "file" || ok=0
    done <<EOF
$(_ctx_copilot_home_shared_files)
EOF

    local d
    while IFS= read -r d; do
        [ -z "$d" ] && continue
        _ctx_reconcile_symlink "$home_dir" "$d" "$copilot_dir/$d" "dir" || ok=0
    done <<EOF
$(_ctx_copilot_home_shared_dirs)
EOF

    if [ "$ok" -ne 1 ]; then
        printf 'ctx: warning: one or more COPILOT_HOME symlinks could not be created; leaving COPILOT_HOME unset for this session\n' >&2
        return 1
    fi

    # Reconcile skills/: desired (name -> target) pairs come from each
    # resolved dir's .github/skills subfolder, if present.
    local -A desired_skills=()
    local -a desired_skill_names=()
    local rd skill_dir sname
    for rd in "${resolved_dirs[@]}"; do
        skill_dir="$rd/.github/skills"
        [ -d "$skill_dir" ] || continue
        local s
        while IFS= read -r s; do
            sname="$(basename "$s")"
            [ -n "${desired_skills[$sname]+set}" ] || desired_skill_names+=("$sname")
            desired_skills[$sname]="${s%/}"
        done < <(find "$skill_dir" -mindepth 1 -maxdepth 1 -type d -print)
    done

    # Remove stale skill symlinks no longer in desired set.
    if [ -d "$home_dir/skills" ]; then
        local existing
        while IFS= read -r existing; do
            local ename
            ename="$(basename "$existing")"
            if [ -z "${desired_skills[$ename]:-}" ]; then
                # Skills are directory symlinks; rm -rf mirrors
                # _ctx_reconcile_symlink and the PowerShell equivalent
                # (Remove-Item -Recurse -Force).
                rm -rf "$existing"
            fi
        done < <(find "$home_dir/skills" -mindepth 1 -maxdepth 1 -print)
    fi

    # Create/repair desired skill symlinks (idempotent).
    local name target link
    for name in "${desired_skill_names[@]}"; do
        target="${desired_skills[$name]}"
        link="$home_dir/skills/$name"
        if [ -L "$link" ] && [ "$(readlink "$link")" = "$target" ]; then
            continue
        fi
        rm -rf "$link"
        if ! ln -s "$target" "$link" 2>/dev/null; then
            printf 'ctx: warning: could not create skill symlink %s -> %s\n' "$link" "$target" >&2
        fi
    done

    export COPILOT_HOME="$home_dir"
    return 0
}

_ctx_update_skill_directories() {
    # Merges the given skill directories (remaining args) into the
    # "skillDirectories" array of .github/copilot/settings.local.json located
    # under $1 (the directory containing the .ctx file). Creates the file
    # (and any missing parent directories) if it does not already exist.
    # Preserves any other keys, and any pre-existing skillDirectories entries,
    # already in the file.
    local base_dir="$1"
    shift
    [ "$#" -eq 0 ] && return 0

    local settings_dir="$base_dir/.github/copilot"
    local settings_file="$settings_dir/settings.local.json"

    local python_bin=""
    if command -v python3 >/dev/null 2>&1; then
        python_bin="python3"
    elif command -v python >/dev/null 2>&1; then
        python_bin="python"
    else
        printf 'ctx: warning: python3 not found; cannot update %s with skill directories\n' "$settings_file" >&2
        return 0
    fi

    mkdir -p "$settings_dir"

    "$python_bin" - "$settings_file" "$@" <<'PYEOF'
import json
import sys

settings_file = sys.argv[1]
new_dirs = sys.argv[2:]

settings = {}
try:
    with open(settings_file, "r", encoding="utf-8") as f:
        content = f.read().strip()
        if content:
            settings = json.loads(content)
except (FileNotFoundError, json.JSONDecodeError):
    settings = {}

if not isinstance(settings, dict):
    settings = {}

existing = settings.get("skillDirectories") or []
if not isinstance(existing, list):
    existing = []

merged = list(dict.fromkeys(existing + new_dirs))
settings["skillDirectories"] = merged

with open(settings_file, "w", encoding="utf-8") as f:
    json.dump(settings, f, indent=2)
    f.write("\n")
PYEOF
}

_ctx_update_workspace_file() {
    # Creates/updates a "<folder-name>.code-workspace" file next to the .ctx
    # file (under $1, the directory containing the .ctx file) so the project
    # and its .ctx dependencies can be browsed together in VS Code: this
    # folder is added as "root: <name>", and each .ctx entry (remaining
    # args, given as alternating name/path pairs) is added as
    # "ctx: <context-name>". Folders not generated by ctx (i.e. not named
    # "root: ..." / "ctx: ...") are left untouched; other top-level keys
    # (settings, extensions, ...) already in the file are preserved.
    local base_dir="$1"
    shift
    local folder_name
    folder_name="$(basename "$base_dir")"
    local workspace_file="$base_dir/$folder_name.code-workspace"

    local python_bin=""
    if command -v python3 >/dev/null 2>&1; then
        python_bin="python3"
    elif command -v python >/dev/null 2>&1; then
        python_bin="python"
    else
        printf 'ctx: warning: python3 not found; cannot update %s with workspace folders\n' "$workspace_file" >&2
        return 0
    fi

    "$python_bin" - "$workspace_file" "$folder_name" "$@" <<'PYEOF'
import json
import os
import sys

workspace_file = sys.argv[1]
folder_name = sys.argv[2]
rest = sys.argv[3:]
workspace_existed = os.path.exists(workspace_file)

pairs = [(rest[i], rest[i + 1]) for i in range(0, len(rest), 2)]

workspace = {}
try:
    with open(workspace_file, "r", encoding="utf-8") as f:
        content = f.read().strip()
        if content:
            workspace = json.loads(content)
except (FileNotFoundError, json.JSONDecodeError):
    workspace = {}

if not isinstance(workspace, dict):
    workspace = {}

existing = workspace.get("folders") or []
if not isinstance(existing, list):
    existing = []

user_folders = [
    f for f in existing
    if not (isinstance(f, dict) and isinstance(f.get("name"), str)
            and (f["name"].startswith("root: ") or f["name"].startswith("ctx: ")))
]

root_entry = {"path": ".", "name": f"root: {folder_name}"}
ctx_entries = [{"path": path, "name": f"ctx: {name}"} for name, path in pairs]

workspace["folders"] = [root_entry] + ctx_entries + user_folders
workspace.setdefault("settings", {})
if not workspace_existed:
    workspace["generatedBy"] = "ctx"

with open(workspace_file, "w", encoding="utf-8") as f:
    json.dump(workspace, f, indent=2)
    f.write("\n")
PYEOF
}

_ctx_parse_ctx_file() {
    # Side-effect-free parser shared by activation and read-only check. Results
    # are exposed in _ctx_parsed_* globals only after complete validation.
    local ctx_file="$1" dir_of_file line name entry_path resolved_path canonical_path profile_path label_lc
    local ai_context="" first_name="" home_override="" noautoload=0
    local -a dirs=() names=() pairs=()
    local -A seen_labels=() seen_targets=()
    dir_of_file="$(dirname "$ctx_file")"
    while IFS= read -r line || [ -n "$line" ]; do
        line="${line%$'\r'}"; [ -z "$line" ] && continue
        case "$line" in '#'*) continue ;; esac
        case "$(_ctx_lowercase "$line")" in noautoload) noautoload=1; continue ;; esac
        case "$line" in *:*) : ;; *) printf 'ctx: error: invalid .ctx line in %s (expected <name>:<path>): %s\n' "$ctx_file" "$line" >&2; return 1 ;; esac
        name="${line%%:*}"; entry_path="${line#*:}"
        name="${name#"${name%%[![:space:]]*}"}"; name="${name%"${name##*[![:space:]]}"}"
        entry_path="${entry_path#"${entry_path%%[![:space:]]*}"}"; entry_path="${entry_path%"${entry_path##*[![:space:]]}"}"
        if [ -z "$name" ] || [ -z "$entry_path" ]; then printf 'ctx: error: invalid .ctx line in %s (expected <name>:<path>): %s\n' "$ctx_file" "$line" >&2; return 1; fi
        label_lc="$(_ctx_lowercase "$name")"
        if [ "$label_lc" != home ]; then
            if [ -n "${seen_labels[$label_lc]+set}" ]; then printf 'ctx: error: duplicate .ctx entry label "%s"; first declared as "%s"\n' "$name" "${seen_labels[$label_lc]}" >&2; return 1; fi
            seen_labels[$label_lc]="$name"
        fi
        if [ "$entry_path" = '@profile' ]; then
            if ! profile_path="$(_ctx_resolve_profile_identifier "$name")"; then return 1; fi
            resolved_path="$profile_path"
        else
            case "$entry_path" in /*) resolved_path="$entry_path" ;; *) resolved_path="$dir_of_file/$entry_path" ;; esac
        fi
        if [ "$label_lc" = home ]; then
            if [ -n "$home_override" ]; then printf 'ctx: error: duplicate "home:" directive in %s\n' "$ctx_file" >&2; return 1; fi
            if ! home_override="$(_ctx_validate_home_path "$resolved_path")"; then return 1; fi
            continue
        fi
        if [ ! -d "$resolved_path" ]; then printf 'ctx: error: .ctx entry "%s" in %s points to missing directory: %s\n' "$name" "$ctx_file" "$resolved_path" >&2; return 1; fi
        canonical_path="$(realpath -m -- "$resolved_path" 2>/dev/null)" || return 1
        if [ -n "${seen_targets[$canonical_path]+set}" ]; then printf 'ctx: error: .ctx entries "%s" and "%s" resolve to the same directory\n' "${seen_targets[$canonical_path]}" "$name" >&2; return 1; fi
        seen_targets[$canonical_path]="$name"; names+=("$name"); dirs+=("$resolved_path"); pairs+=("$name" "$resolved_path")
        [ -z "$ai_context" ] && { ai_context="$name"; first_name="$name"; } || ai_context="$ai_context+$name"
    done < "$ctx_file"
    if [ "${#names[@]}" -eq 0 ]; then printf 'ctx: error: .ctx file is empty or invalid: %s\n' "$ctx_file" >&2; return 1; fi
    _ctx_parsed_dir="$dir_of_file"; _ctx_parsed_context="$ai_context"; _ctx_parsed_first_name="$first_name"; _ctx_parsed_home="$home_override"; _ctx_parsed_noautoload="$noautoload"
    _ctx_parsed_names=("${names[@]}"); _ctx_parsed_dirs=("${dirs[@]}"); _ctx_parsed_pairs=("${pairs[@]}")
}

_ctx_load_ctx_file() {
    local ctx_file="$1" dirs_csv shared_csv
    _ctx_parse_ctx_file "$ctx_file" || return 1
    dirs_csv="$(IFS=,; printf '%s' "${_ctx_parsed_dirs[*]}")"
    _ctx_update_workspace_file "$_ctx_parsed_dir" "${_ctx_parsed_pairs[@]}"
    export AI_CTX_PROFILES="$_ctx_parsed_context" COPILOT_CUSTOM_INSTRUCTIONS_DIRS="$dirs_csv"
    _ctx_setup_copilot_home "$_ctx_parsed_context" "$_ctx_parsed_home" "${_ctx_parsed_dirs[@]}" || return 1
    _ctx_auto_load_home_override="$_ctx_parsed_home"
    if [ "$_ctx_parsed_context" = "$_ctx_parsed_first_name" ]; then shared_csv=""; else shared_csv="${_ctx_parsed_context#*+}"; shared_csv="${shared_csv//+/, }"; fi
    _ctx_print_status "$_ctx_parsed_first_name" "$shared_csv" "$dirs_csv"
}
_ctx_check() {
    local ctx_file dir_of_file line name entry_path resolved_path home_override=""
    local expected_context="" expected_dirs="" first=1 profile_lookup
    local -a names=() dirs=()
    local failures=0
    local -A seen_labels=() seen_targets=()

    if ! ctx_file="$(_ctx_find_ctx_file)"; then
        printf 'ctx check: no .ctx file found; nothing to check\n'
        return 0
    fi
    if ! _ctx_parse_ctx_file "$ctx_file"; then
        printf 'CHECK FAIL parser: invalid .ctx file\n'
        return 1
    fi
    dir_of_file="$_ctx_parsed_dir"; expected_context="$_ctx_parsed_context"; home_override="$_ctx_parsed_home"
    names=("${_ctx_parsed_names[@]}"); dirs=("${_ctx_parsed_dirs[@]}")
    expected_dirs="$(IFS=,; printf '%s' "${dirs[*]}")"
    if [ "${AI_CTX_PROFILES:-}" = "$expected_context" ]; then printf 'CHECK PASS AI_CTX_PROFILES\n'; else printf 'CHECK FAIL AI_CTX_PROFILES: expected %s, got %s\n' "$expected_context" "${AI_CTX_PROFILES:-<unset>}"; failures=$((failures+1)); fi
    if [ "${COPILOT_CUSTOM_INSTRUCTIONS_DIRS:-}" = "$expected_dirs" ]; then printf 'CHECK PASS COPILOT_CUSTOM_INSTRUCTIONS_DIRS\n'; else printf 'CHECK FAIL COPILOT_CUSTOM_INSTRUCTIONS_DIRS: expected %s, got %s\n' "$expected_dirs" "${COPILOT_CUSTOM_INSTRUCTIONS_DIRS:-<unset>}"; failures=$((failures+1)); fi

    local expected_home
    if [ -n "$home_override" ]; then expected_home="$home_override"; else expected_home="$(_ctx_copilot_home_root)/$(_ctx_sanitize_context_name "$expected_context")"; fi
    if [ "${COPILOT_HOME:-}" = "$expected_home" ] && [ -d "$expected_home" ]; then printf 'CHECK PASS COPILOT_HOME\n'; else printf 'CHECK FAIL COPILOT_HOME: expected %s, got %s\n' "$expected_home" "${COPILOT_HOME:-<unset>}"; failures=$((failures+1)); fi

    local f target current
    while IFS= read -r f; do
        [ -z "$f" ] && continue
        target="${CTX_COPILOT_DIR:-$HOME/.copilot}/$f"
        if _ctx_link_matches "$expected_home/$f" "$target"; then printf 'CHECK PASS link:%s\n' "$f"; else printf 'CHECK FAIL link:%s: expected link to %s\n' "$f" "$target"; failures=$((failures+1)); fi
    done <<EOF
$(_ctx_copilot_home_shared_files)
EOF
    while IFS= read -r f; do
        [ -z "$f" ] && continue
        target="${CTX_COPILOT_DIR:-$HOME/.copilot}/$f"
        if _ctx_link_matches "$expected_home/$f" "$target"; then printf 'CHECK PASS link:%s\n' "$f"; else printf 'CHECK FAIL link:%s: expected link to %s\n' "$f" "$target"; failures=$((failures+1)); fi
    done <<EOF
$(_ctx_copilot_home_shared_dirs)
EOF

    local -A desired=() actual=()
    local -a desired_names=() actual_names=()
    local rd skill_dir s skill_name
    for rd in "${dirs[@]}"; do
        skill_dir="$rd/.github/skills"
        [ -d "$skill_dir" ] || continue
        while IFS= read -r s; do
            skill_name="$(basename "$s")"
            [ -n "${desired[$skill_name]+set}" ] || desired_names+=("$skill_name")
            desired["$skill_name"]="${s%/}"
        done < <(find "$skill_dir" -mindepth 1 -maxdepth 1 -type d -print)
    done
    while IFS= read -r s; do
        skill_name="$(basename "$s")"
        actual_names+=("$skill_name")
        actual["$skill_name"]="$(readlink "$s" 2>/dev/null || printf '%s' plain)"
    done < <(find "$expected_home/skills" -mindepth 1 -maxdepth 1 -print)
    local sorted_skills
    sorted_skills="$(printf '%s\n' "${desired_names[@]}" | sort)"
    while IFS= read -r skill_name; do
        [ -n "$skill_name" ] || continue
        if [ "${actual[$skill_name]:-}" = "${desired[$skill_name]}" ]; then printf 'CHECK PASS skill:%s\n' "$skill_name"; else printf 'CHECK FAIL skill:%s: missing or wrong target\n' "$skill_name"; failures=$((failures+1)); fi
    done <<< "$sorted_skills"
    sorted_skills="$(printf '%s\n' "${actual_names[@]}" | sort)"
    while IFS= read -r skill_name; do
        [ -n "$skill_name" ] || continue
        [ -n "${desired[$skill_name]:-}" ] || { printf 'CHECK FAIL skill:%s: unexpected skill\n' "$skill_name"; failures=$((failures+1)); }
    done <<< "$sorted_skills"

    # Strict check is read-only: do not invoke external copilot commands.
    # Even a seemingly informational probe may write caches/state.
    printf 'CHECK SKIP skills: copilot probe disabled in read-only check\n'

    local workspace="$dir_of_file/$(basename "$dir_of_file").code-workspace"
    if [ -e "$workspace" ] && [ ! -L "$workspace" ]; then
        local workspace_bin=""
        if command -v python3 >/dev/null 2>&1; then workspace_bin="python3"; elif command -v python >/dev/null 2>&1; then workspace_bin="python"; fi
        if [ -z "$workspace_bin" ]; then
            printf 'CHECK SKIP workspace: no python interpreter available\n'
        elif "$workspace_bin" - "$workspace" "${names[@]}" "${dirs[@]}" <<'PYEOF'
import json, sys
p=sys.argv[1]; n=len(sys.argv[2:])//2; names=sys.argv[2:2+n]; dirs=sys.argv[2+n:]
try:
    with open(p, encoding='utf-8') as f: w=json.load(f)
    folders=w.get('folders', []) if isinstance(w,dict) else []
    wanted=[('.', 'root: '+p.rsplit('/',2)[-2])] + list(zip(dirs, ['ctx: '+x for x in names]))
    have={(x.get('path'),x.get('name')) for x in folders if isinstance(x,dict)}
    missing=[x for x in wanted if x not in have]
    print('CHECK PASS workspace marker='+('ctx' if w.get('generatedBy') == 'ctx' else 'unmarked'))
    if missing:
        print('CHECK FAIL workspace: missing expected folder(s)')
        sys.exit(1)
except Exception:
    print('CHECK FAIL workspace: invalid JSON')
    sys.exit(1)
PYEOF
        then :; else failures=$((failures+1)); fi
    else
        printf 'CHECK SKIP workspace: no adjacent workspace file\n'
    fi
    if [ "$failures" -eq 0 ]; then printf 'ctx check: PASS\n'; return 0; fi
    printf 'ctx check: FAIL (%s)\n' "$failures"; return 1
}

# --- Shell integration (completion + chdir hooks) -----------------------

_ctx_list_subdirs() {
    local base="$1"
    [ -d "$base" ] || return 0
    find "$base" -mindepth 1 -maxdepth 1 -type d -exec basename {} \; 2>/dev/null
}

if [ -n "${ZSH_VERSION:-}" ]; then
    # zsh completion
    _ctx_zsh_complete() {
        local root="$(_ctx_root)"
        local -a words_arr
        words_arr=("${words[@]}")
        if [ "${#words_arr[@]}" -eq 3 ] && [ "${words_arr[2]}" = "clear" ]; then
            compadd --all
        elif [ "${#words_arr[@]}" -ge 3 ] && [ "${words_arr[2]}" = "load" ]; then
            _files
        elif [ "${#words_arr[@]}" -le 2 ]; then
            local -a profiles
            profiles=("${(f)$(_ctx_list_subdirs "$root/profiles")}")
            compadd current clear load -- "${profiles[@]}"
        else
            local -a shared
            shared=("${(f)$(_ctx_list_subdirs "$root/profiles")}")
            compadd -- "${shared[@]}"
        fi
    }
    compdef _ctx_zsh_complete ctx 2>/dev/null || true

    autoload -Uz add-zsh-hook 2>/dev/null
    if command -v add-zsh-hook >/dev/null 2>&1; then
        add-zsh-hook chpwd _ctx_auto_load_hook
    fi
    # Run once for the shell's starting directory.
    _ctx_auto_load_hook

elif [ -n "${BASH_VERSION:-}" ]; then
    # bash completion
    _ctx_bash_complete() {
        local root cur
        root="$(_ctx_root)"
        cur="${COMP_WORDS[COMP_CWORD]}"

        if [ "$COMP_CWORD" -eq 1 ]; then
            mapfile -t COMPREPLY < <(compgen -W "current clear load $(_ctx_list_subdirs "$root/profiles" | tr '\n' ' ')" -- "$cur")
        elif [ "$COMP_CWORD" -eq 2 ] && [ "${COMP_WORDS[1]}" = "clear" ]; then
            mapfile -t COMPREPLY < <(compgen -W "--all" -- "$cur")
        elif [ "$COMP_CWORD" -ge 2 ] && [ "${COMP_WORDS[1]}" = "load" ]; then
            mapfile -t COMPREPLY < <(compgen -f -- "$cur")
        else
            mapfile -t COMPREPLY < <(compgen -W "$(_ctx_list_subdirs "$root/profiles" | tr '\n' ' ')" -- "$cur")
        fi
    }
    complete -F _ctx_bash_complete ctx

    _ctx_bash_chpwd() {
        if [ "${_ctx_bash_last_pwd:-}" != "$PWD" ]; then
            _ctx_bash_last_pwd="$PWD"
            _ctx_auto_load_hook
        fi
    }
    case "${PROMPT_COMMAND:-}" in
        *_ctx_bash_chpwd*) : ;;
        "") PROMPT_COMMAND="_ctx_bash_chpwd" ;;
        *) PROMPT_COMMAND="_ctx_bash_chpwd;${PROMPT_COMMAND}" ;;
    esac
    # Run once for the shell's starting directory.
    _ctx_bash_last_pwd="$PWD"
    _ctx_auto_load_hook
fi
